
  $ cat > foo.ml <<EOF
  > [@@@bs.config {flags = [| "-unsafe" |] }]
  > let x = 1
  > EOF

  $ melc foo.ml -as-pp foo.ml > foo.pp.ml
  $ melc --as-ppx foo.pp.ml bar.pp.ml
  melc: `--as-ppx` requires 2 arguments: `melc --as-ppx input output`
  1 | [@@@bs.config {flags = [| "-unsafe" |] }]
                             ^^^^^^^^^^^^^^^
  Error: Invalid configuration
  [2]

  $ melc ./bar.pp.ml
  // Generated by Melange
  /* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */
