A test case for some exn in lam_convert

  $ export MELANGELIB="$INSIDE_DUNE/lib/melange"

  $ cat > x.ml <<EOF
  > let t = (Pervasives.abs_float  [@ocaml.alert "-deprecated"]);
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  
  function t(prim) {
    return Math.abs(prim);
  }
  
  exports.t = t;
  /* No side effect */
