Demonstrate the `#if MELANGE` conditional variable

  $ source ./setup.sh
  $ cat > x.ml <<EOF
  > let () =
  > #if MELANGE then
  >   Js.log("It's Melange");
  > #else
  >   Js.log2("Not Melange, type error, not 2 arguments");
  > #end
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  
  console.log("It's Melange");
  
  /*  Not a pure module */

