Set up a few directories we'll need

  $ . ./setup.sh
  $ mkdir -p lib/.objs/melange
  $ mkdir -p app/.objs/melange
  $ mkdir -p output/lib
  $ mkdir -p output/app

  $ echo "let t = 1" > lib/a.ml

Using Lib__A here just for demoing purposes, Dune gen'd wrapping modules would
make this work with Lib.A.t

  $ echo "let t = Lib__A.t" > app/B.ml

Build cmjs

  $ melc -bs-package-output lib/ -bs-module-name a -bs-stop-after-cmj lib/a.ml -o lib/.objs/melange/lib__A.cmj

  $ melc -bs-package-output app/ -bs-module-name B -I lib/.objs/melange -bs-stop-after-cmj app/B.ml -o app/.objs/melange/melange__B.cmj

Linking step

  $ melc -bs-module-type commonjs lib/.objs/melange/lib__A.cmj -o output/lib/a.js

Note casing is respected:
- module A was produced by a.ml, so output is a.js
- module B was produced by B.ml, so output is B.js

  $ melc -bs-module-type commonjs -I lib/.objs/melange app/.objs/melange/melange__B.cmj -o output/app/B.js

Path should point to proper name of the .js dep

  $ cat output/app/B.js
  // Generated by Melange
  'use strict';
  
  var Lib__A = require("../lib/a.js");
  
  var t = Lib__A.t;
  
  exports.t = t;
  /* No side effect */
