Demonstrate how to use `melc` with `refmt` and Reason files

  $ source ./setup.sh
  $ cat > x.re <<EOF
  > let () =
  >   Js.log2("Here's two:", 2);
  > EOF

  $ melc $MEL_STDLIB_FLAGS -pp 'refmt --print=binary' -impl x.re
  melc: no output specified (use -o <filename>.js)
  [124]

Now specify the output filename with `-o`

  $ melc $MEL_STDLIB_FLAGS -pp 'refmt --print=binary' -impl x.re -o x.js
  $ cat x.js
  // Generated by Melange
  'use strict';
  
  
  console.log("Here's two:", 2);
  
  /*  Not a pure module */
