  $ source ./setup.sh

Set up a few directories we'll need

  $ mkdir -p app
  $ mkdir -p app/.objs/melange
  $ mkdir -p output/app

  $ cat > app/b.ml << EOF
  > let t = ["Hello"] |. Belt.List.map(fun greeting -> greeting)
  > EOF

Compile cmjs

  $ melc $MEL_STDLIB_FLAGS -bs-legacy -bs-package-output app/ app/b.ml -bs-stop-after-cmj -o app/.objs/melange/b.cmj

Emit js

  $ melc $MEL_STDLIB_FLAGS -bs-legacy -bs-module-type es6 app/.objs/melange/b.cmj -o output/app/b.js

Check b.js output

  $ cat output/app/b.js
  // Generated by Melange
  
  import * as Belt_List from "melange/lib/es6/belt_List.mjs";
  
  var t = Belt_List.map({
        hd: "Hello",
        tl: /* [] */0
      }, (function (greeting) {
          return greeting;
        }));
  
  export {
    t ,
  }
  /* t Not a pure module */
