// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";

function g(x) {
  return Curry._1(x._0, x);
}

var loop = g(/* A */{
      _0: g
    });

var x = /* A */{
  _0: g
};

var non_terminate = g(x);

var xx = {};

xx.xx = xx;

export {
  loop ,
  non_terminate ,
}
/* loop Not a pure module */
