// Generated by Melange


var a10 = "hello world";

var v = 1;

var a21 = "hello worldnothello worldnot";

function ff(param) {
  return "cool test hello worldnothello worldnothello";
}

var a23 = ff(undefined);

var a15 = a10;

var b15 = 111;

export {
  a15 ,
  b15 ,
  a21 ,
  v ,
  a23 ,
  ff ,
}
/* a23 Not a pure module */
