// Generated by Melange

import * as Stdlib from "melange.stdlib/jscomp/stdlib-412/stdlib.js";
import * as Caml_array from "melange/lib/es6/caml_array.mjs";
import * as Caml_js_exceptions from "melange/lib/es6/caml_js_exceptions.mjs";

var x = [
  1,
  2
];

var y;

try {
  y = Caml_array.get(x, 3);
}
catch (raw_msg){
  var msg = Caml_js_exceptions.internalToOCamlException(raw_msg);
  if (msg.RE_EXN_ID === Stdlib.Invalid_argument) {
    console.log(msg._1);
    y = 0;
  } else {
    throw msg;
  }
}

export {
  x ,
  y ,
}
/* y Not a pure module */
