// Generated by Melange

import * as Caml_option from "melange/lib/es6/caml_option.mjs";

function treeHeight(n) {
  if (n !== undefined) {
    return Caml_option.valFromOption(n).height;
  } else {
    return 0;
  }
}

function copy(n) {
  if (n === undefined) {
    return n;
  }
  var match = Caml_option.valFromOption(n);
  var v = match.value;
  var h = match.height;
  var l = match.left;
  var r = match.right;
  return {
          value: v,
          height: h,
          left: copy(l),
          right: copy(r)
        };
}

export {
  treeHeight ,
  copy ,
}
/* No side effect */
