// Generated by Melange

import * as Mt from "./mt.js";
import * as Test_bool_equal from "./test_bool_equal.js";

Mt.from_suites("boolean", {
      hd: [
        "bool_equal",
        Test_bool_equal.assertions
      ],
      tl: /* [] */0
    });

export {
  
}
/*  Not a pure module */
