// Generated by Melange


function fff(x) {
  x.height = 2;
}

function ff(x, z) {
  return {
          hd: x.height,
          tl: {
            hd: z.height,
            tl: /* [] */0
          }
        };
}

export {
  fff ,
  ff ,
}
/* No side effect */
