// Generated by Melange

import * as Mt from "./mt.js";

var v = {
  contents: 1
};

v.contents = v.contents + 1 | 0;

var a = v.contents;

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

eq("File \"condition_compilation_test.ml\", line 98, characters 5-12", 3, 3);

eq("File \"condition_compilation_test.ml\", line 99, characters 5-12", v.contents, 2);

Mt.from_pair_suites("Condition_compilation_test", suites.contents);

var b = "u";

var buffer_size = 1;

var vv = 3;

var version_gt_3 = true;

var version = -1;

var ocaml_veriosn = "unknown";

export {
  b ,
  buffer_size ,
  vv ,
  v ,
  a ,
  version_gt_3 ,
  version ,
  ocaml_veriosn ,
  suites ,
  test_id ,
  eq ,
}
/*  Not a pure module */
