// Generated by Melange

import * as Caml_obj from "melange/lib/es6/caml_obj.mjs";

function min_int(prim0, prim1) {
  return Math.min(prim0, prim1);
}

function say(prim0, prim1) {
  return prim1.say(prim0);
}

var v = Caml_obj.caml_compare;

export {
  min_int ,
  say ,
  v ,
}
/* No side effect */
