// Generated by Melange


var u = 3;

function f(param) {
  throw {
        RE_EXN_ID: "Invalid_argument",
        _1: "hi",
        Error: new Error()
      };
}

export {
  u ,
  f ,
}
/* No side effect */
