// Generated by Melange


function register(rl) {
  return rl.on("line", (function (x) {
                  console.log(x);
                })).on("close", (function (param) {
                console.log("finished");
              }));
}

export {
  register ,
}
/* No side effect */
