// Generated by Melange


function u_x(param) {
  return param.u_x;
}

function b_x(param) {
  return param.b_x;
}

function c_x(param) {
  return param.c_x;
}

function d_int(param_0) {
  return {
          TAG: /* D_int */0,
          _0: param_0
        };
}

function d_tuple(param_0, param_1) {
  return {
          TAG: /* D_tuple */1,
          _0: param_0,
          _1: param_1
        };
}

function newContent(param_0) {
  return {
          TAG: /* NewContent */2,
          _0: param_0
        };
}

function d_tweak(param_0) {
  return {
          TAG: /* D_tweak */3,
          _0: param_0
        };
}

function u_X(param) {
  return param.u_X;
}

function d(param) {
  return param.d;
}

var v = {
  TAG: /* D_int */0,
  _0: 3
};

var h_1 = {
  hd: {
    TAG: /* D_int */0,
    _0: 3
  },
  tl: {
    hd: {
      TAG: /* D_tuple */1,
      _0: 3,
      _1: "hgo"
    },
    tl: {
      hd: {
        TAG: /* D_tweak */3,
        _0: [
          3,
          "hgo"
        ]
      },
      tl: {
        hd: {
          TAG: /* NewContent */2,
          _0: "3"
        },
        tl: /* [] */0
      }
    }
  }
};

var h = {
  hd: /* D_empty */0,
  tl: h_1
};

function xx(param_0) {
  return /* Xx */{
          _0: param_0
        };
}

function a(param_0) {
  return /* A */{
          _0: param_0
        };
}

var d_empty = /* D_empty */0;

var hei = /* Hei */0;

export {
  u_x ,
  b_x ,
  c_x ,
  d_empty ,
  d_int ,
  d_tuple ,
  newContent ,
  d_tweak ,
  hei ,
  u_X ,
  d ,
  v ,
  h ,
  xx ,
  a ,
}
/* No side effect */
