// Generated by Melange

import * as Stdlib from "melange.stdlib/jscomp/stdlib-412/stdlib.js";
import * as Exception_def from "./exception_def.js";
import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var E = /* @__PURE__ */Caml_exceptions.create("Exception_rebind_test.A.E");

var A = {
  E: E
};

var B = {
  F: E
};

var A0 = /* @__PURE__ */Caml_exceptions.create("Exception_rebind_test.A0");

var u0 = {
  RE_EXN_ID: Stdlib.Invalid_argument,
  _1: "x"
};

var u1 = {
  RE_EXN_ID: Stdlib.Invalid_argument,
  _1: "x"
};

var u2 = {
  RE_EXN_ID: Stdlib.Not_found
};

var H = Exception_def.A;

var H0 = Stdlib.Invalid_argument;

var H1 = Stdlib.Invalid_argument;

export {
  A ,
  B ,
  H ,
  A0 ,
  H0 ,
  H1 ,
  u0 ,
  u1 ,
  u2 ,
}
/* Exception_def Not a pure module */
