// Generated by Melange

import * as Sys from "melange/jscomp/stdlib-412/stdlib_modules/sys.js";

var is_windows_or_cygwin = Sys.win32 || false;

export {
  is_windows_or_cygwin ,
}
/* No side effect */
