// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Caml_external_polyfill from "melange/lib/es6/caml_external_polyfill.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

require('melange/lib/js/caml_external_polyfill.js').register("caml_fancy_add", function(x,y){
  return + ((""+x ) + (""+y))
})
;

var h = Caml_external_polyfill.resolve("caml_fancy_add")(1, 2);

eq("File \"external_polyfill_test.ml\", line 19, characters 5-12", h, 12);

Mt.from_pair_suites("External_polyfill_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  h ,
}
/*  Not a pure module */
