// Generated by Melange

import * as External_ppxGen from "./external_ppx.gen";

var u = {
  hi: 2,
  lo: 3,
  lo2: {hi:-3 },
  lo3: -1,
  lo4: -3
};

function f(prim) {
  return External_ppxGen.f(prim);
}

export {
  u ,
  f ,
}
/* ./external_ppx.gen Not a pure module */
