// Generated by Melange

import * as Mt from "./mt.mjs";
import * as List from "melange/jscomp/stdlib-412/stdlib_modules/list.mjs";
import * as $$Array from "melange/jscomp/stdlib-412/stdlib_modules/array.mjs";
import * as Curry from "melange/lib/es6/curry.mjs";
import * as Printf from "melange/jscomp/stdlib-412/stdlib_modules/printf.mjs";
import * as Stdlib from "melange.stdlib/jscomp/stdlib-412/stdlib.mjs";
import * as Caml_float from "melange/lib/es6/caml_float.mjs";
import * as Caml_int64 from "melange/lib/es6/caml_int64.mjs";

var one_float = [
  1072693248,
  0
];

var int32_pairs = [
  [
    32,
    4.48415508583941463e-44
  ],
  [
    3,
    4.20389539297445121e-45
  ]
];

function from_pairs(pair) {
  return List.concat($$Array.to_list($$Array.mapi((function (i, param) {
                        var f = param[1];
                        var i32 = param[0];
                        return {
                                hd: [
                                  Curry._1(Printf.sprintf(/* Format */{
                                            _0: {
                                              TAG: /* String_literal */11,
                                              _0: "int32_float_of_bits ",
                                              _1: {
                                                TAG: /* Int */4,
                                                _0: /* Int_d */0,
                                                _1: /* No_padding */0,
                                                _2: /* No_precision */0,
                                                _3: /* End_of_format */0
                                              }
                                            },
                                            _1: "int32_float_of_bits %d"
                                          }), i),
                                  (function (param) {
                                      return {
                                              TAG: /* Eq */0,
                                              _0: Caml_float.caml_int32_float_of_bits(i32),
                                              _1: f
                                            };
                                    })
                                ],
                                tl: {
                                  hd: [
                                    Curry._1(Printf.sprintf(/* Format */{
                                              _0: {
                                                TAG: /* String_literal */11,
                                                _0: "int32_bits_of_float ",
                                                _1: {
                                                  TAG: /* Int */4,
                                                  _0: /* Int_d */0,
                                                  _1: /* No_padding */0,
                                                  _2: /* No_precision */0,
                                                  _3: /* End_of_format */0
                                                }
                                              },
                                              _1: "int32_bits_of_float %d"
                                            }), i),
                                    (function (param) {
                                        return {
                                                TAG: /* Eq */0,
                                                _0: Caml_float.caml_int32_bits_of_float(f),
                                                _1: i32
                                              };
                                      })
                                  ],
                                  tl: /* [] */0
                                }
                              };
                      }), int32_pairs)));
}

var suites = Stdlib.$at({
      hd: [
        "one",
        (function (param) {
            return {
                    TAG: /* Eq */0,
                    _0: Caml_int64.bits_of_float(1.0),
                    _1: one_float
                  };
          })
      ],
      tl: {
        hd: [
          "two",
          (function (param) {
              return {
                      TAG: /* Eq */0,
                      _0: Caml_int64.float_of_bits(one_float),
                      _1: 1.0
                    };
            })
        ],
        tl: /* [] */0
      }
    }, from_pairs(int32_pairs));

Mt.from_pair_suites("Float_of_bits_test", suites);

export {
  one_float ,
  int32_pairs ,
  from_pairs ,
  suites ,
}
/* suites Not a pure module */
