// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Fs from "fs";
import * as Path from "path";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, param) {
  var y = param[1];
  var x = param[0];
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

var x = typeof __filename === "undefined" ? undefined : __filename;

var current_file = x !== undefined ? x : "<Not Node JS>";

var x$1 = typeof __dirname === "undefined" ? undefined : __dirname;

var current_dir_name = x$1 !== undefined ? x$1 : "<Not Node Js>";

Fs.readFileSync(current_file, "utf8");

Fs.readdirSync(current_dir_name);

var pathobj = Path.parse(current_dir_name);

var module_ = typeof module === "undefined" ? undefined : module;

if (module_ !== undefined) {
  console.log([
        module_.id,
        module_.paths
      ]);
  eq("File \"fs_test.ml\", line 45, characters 7-14", [
        pathobj.name,
        "test"
      ]);
}

Mt.from_pair_suites("Fs_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
}
/* x Not a pure module */
