// Generated by Melange

import * as Caml_option from "melange/lib/es6/caml_option.mjs";

function Make(S) {
  var opt_get = function (f, i) {
    return Caml_option.undefined_to_opt(f[i]);
  };
  return {
          opt_get: opt_get
        };
}

function opt_get(f, i) {
  return Caml_option.undefined_to_opt(f[i]);
}

var Int_arr = {
  opt_get: opt_get
};

function f(v) {
  return [
          v[0],
          Caml_option.undefined_to_opt(v[1])
        ];
}

export {
  Make ,
  Int_arr ,
  f ,
}
/* No side effect */
