// Generated by Melange

import * as Mt from "./mt.js";
import * as Curry from "melange/lib/es6/curry.mjs";
import * as Functor_def from "./functor_def.js";
import * as Functor_inst from "./functor_inst.js";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

var Y0 = Functor_def.Make(Functor_inst);

var Y1 = Functor_def.Make(Functor_inst);

eq("File \"functor_app_test.ml\", line 23, characters 6-13", Curry._2(Y0.h, 1, 2), 4);

eq("File \"functor_app_test.ml\", line 24, characters 6-13", Curry._2(Y1.h, 2, 3), 6);

var v = Functor_def.$$return(undefined);

eq("File \"functor_app_test.ml\", line 29, characters 6-13", v, 2);

Mt.from_pair_suites("Functor_app_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  Y0 ,
  Y1 ,
  v ,
}
/* Y0 Not a pure module */
