// Generated by Melange


var $$__dirname = 1;

var $$__filename = 2;

var $$clearImmediate = 3;

var $$clearInterval = 4;

var $$clearTimeout = 5;

var $$console = 6;

var $$exports = 7;

var $$global = 8;

var _module = 9;

var $$process = 10;

var $$require = 11;

var $$setImmediate = 12;

var $$setInterval = 13;

var $$setTimeout = 14;

export {
  $$__dirname ,
  $$__filename ,
  $$clearImmediate ,
  $$clearInterval ,
  $$clearTimeout ,
  $$console ,
  $$exports ,
  $$global ,
  _module ,
  $$process ,
  $$require ,
  $$setImmediate ,
  $$setInterval ,
  $$setTimeout ,
}
/* No side effect */
