// Generated by Melange

import * as Mt from "./mt.js";
import * as Test_google_closure from "./test_google_closure.js";

Mt.from_pair_suites("Closure", {
      hd: [
        "partial",
        (function (param) {
            return {
                    TAG: /* Eq */0,
                    _0: [
                      Test_google_closure.a,
                      Test_google_closure.b,
                      Test_google_closure.c
                    ],
                    _1: [
                      "3",
                      101,
                      [
                        1,
                        2
                      ]
                    ]
                  };
          })
      ],
      tl: /* [] */0
    });

export {
  
}
/*  Not a pure module */
