// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Belt_MutableMapInt from "melange.runtime-others/jscomp/others/belt_MutableMapInt.mjs";
import * as Belt_internalMapInt from "melange.runtime-others/jscomp/others/belt_internalMapInt.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

var mockMap = {
  data: undefined
};

function add(id) {
  Belt_MutableMapInt.set(mockMap, id, id);
  return id;
}

function remove(id) {
  Belt_MutableMapInt.remove(mockMap, id);
}

add(1726);

var n = add(6667);

add(486);

Belt_MutableMapInt.remove(mockMap, 1726);

var n1 = Belt_internalMapInt.getExn(mockMap.data, 6667);

eq("File \"gpr_4265_test.ml\", line 17, characters 6-13", n, n1);

Mt.from_pair_suites("gpr_4265_test.ml", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  mockMap ,
  add ,
  remove ,
  n ,
  n1 ,
}
/*  Not a pure module */
