// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";

function foo(x) {
  if (typeof x === "string" || !(x.NAME === "Foo" && x.VAL === 3)) {
    console.log("2");
  } else {
    console.log("1");
  }
}

function foo2(x) {
  if (typeof x === "string" || !(x.NAME === "Foo" && x.VAL === 3)) {
    return "xxx";
  } else {
    return "xxxx";
  }
}

function foo3(x) {
  if (typeof x === "string" || !(x.NAME === "Foo" && x.VAL === 3)) {
    return 2;
  } else {
    return 1;
  }
}

function foo4(x, h) {
  if (typeof x === "string" || !(x.NAME === "Foo" && x.VAL === 3)) {
    return ;
  } else {
    return Curry._1(h, undefined);
  }
}

function foo5(x) {
  if (typeof x === "string" || !(x.NAME === "Foo" && x.VAL === 3)) {
    console.log("x");
  } else {
    console.log("hi");
  }
}

export {
  foo ,
  foo2 ,
  foo3 ,
  foo4 ,
  foo5 ,
}
/* No side effect */
