// Generated by Melange

import * as Belt_MutableSetInt from "melange.runtime-others/jscomp/others/belt_MutableSetInt.mjs";

var mySet = {
  data: undefined
};

Belt_MutableSetInt.add(mySet, 1);

Belt_MutableSetInt.add(mySet, 2);

Belt_MutableSetInt.remove(mySet, 1);

var a = 3;

export {
  mySet ,
  a ,
}
/*  Not a pure module */
