// Generated by Melange

import * as $$Array from "melange/jscomp/stdlib-412/stdlib_modules/array.js";
import * as Curry from "melange/lib/es6/curry.mjs";
import * as Caml_module from "melange/lib/es6/caml_module.mjs";

var PA = Caml_module.init_mod([
      "gpr_3931_test.ml",
      3,
      6
    ], {
      TAG: /* Module */0,
      _0: [[
          /* Function */0,
          "print"
        ]]
    });

var P = Caml_module.init_mod([
      "gpr_3931_test.ml",
      11,
      6
    ], {
      TAG: /* Module */0,
      _0: [[
          /* Function */0,
          "print"
        ]]
    });

function print(a) {
  $$Array.iter(P.print, a);
}

Caml_module.update_mod({
      TAG: /* Module */0,
      _0: [[
          /* Function */0,
          "print"
        ]]
    }, PA, {
      print: print
    });

function print$1(i) {
  console.log(String(i));
}

Caml_module.update_mod({
      TAG: /* Module */0,
      _0: [[
          /* Function */0,
          "print"
        ]]
    }, P, {
      print: print$1
    });

Curry._1(PA.print, [
      1,
      2
    ]);

export {
  PA ,
  P ,
}
/* PA Not a pure module */
