// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";
import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";
import * as Caml_js_exceptions from "melange/lib/es6/caml_js_exceptions.mjs";

var x = {
  contents: 1
};

var y = {
  contents: 2
};

function f(param) {
  var a = {
    contents: param[0]
  };
  var b = {
    contents: param[1]
  };
  console.log(a, b);
}

function g(param) {
  return 3;
}

function a0(f) {
  var u = Curry._1(f, undefined);
  if (u !== null) {
    console.log(u);
    console.log(u);
    return 1;
  } else {
    return 0;
  }
}

function a1(f) {
  var E = /* @__PURE__ */Caml_exceptions.create("E");
  try {
    return Curry._1(f, undefined);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === E) {
      return 1;
    }
    throw exn;
  }
}

var a = 1;

var b = 2;

export {
  a ,
  b ,
  x ,
  y ,
  f ,
  g ,
  a0 ,
  a1 ,
}
/* No side effect */
