// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Int64 from "melange/jscomp/stdlib-412/stdlib_modules/int64.mjs";
import * as Stdlib from "melange.stdlib/jscomp/stdlib-412/stdlib.mjs";
import * as Caml_int64 from "melange/lib/es6/caml_int64.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

function f(x) {
  Stdlib.print_string("f");
  return x;
}

function g(x) {
  return Caml_int64.or_(x, (Stdlib.print_string("f"), x));
}

var v = {
  contents: 0
};

function f2(x) {
  v.contents = v.contents + 1 | 0;
  return x;
}

function g2(x) {
  return Caml_int64.or_(x, (v.contents = v.contents + 1 | 0, x));
}

var a = Caml_int64.or_(Int64.one, (v.contents = v.contents + 1 | 0, Int64.one));

eq("File \"gpr_1154_test.ml\", line 27, characters 12-19", v.contents, 1);

Mt.from_pair_suites("Gpr_1154_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  f ,
  g ,
  v ,
  f2 ,
  g2 ,
  a ,
}
/* a Not a pure module */
