// Generated by Melange

import * as Belt_List from "melange.runtime-others/jscomp/others/belt_List.mjs";
import * as Belt_Array from "melange.runtime-others/jscomp/others/belt_Array.mjs";

var N = {};

function f(X) {
  return function (xs) {
    X.forEach(xs, {
          i: (function (x) {
              console.log(x.x);
            })
        });
  };
}

Belt_List.forEachU({
      hd: {
        x: 3
      },
      tl: /* [] */0
    }, (function (x) {
        console.log(x.x);
      }));

var Foo = {};

var bar = [{
    foo: "bar"
  }];

Belt_Array.mapU(bar, (function (b) {
        return b.foo;
      }));

export {
  N ,
  f ,
  Foo ,
  bar ,
}
/*  Not a pure module */
