// Generated by Melange

import * as Mt from "./mt.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

Mt.from_pair_suites("Gpr_2789_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
}
/*  Not a pure module */
