// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Caml_obj from "melange/lib/es6/caml_obj.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

var a = {};

var b = {};

Caml_obj.update_dummy(a, {
      b: b
    });

Caml_obj.update_dummy(b, {
      a: a
    });

function is_inifite(x) {
  return x.b.a === x;
}

eq("File \"gpr_1716_test.ml\", line 26, characters 6-13", true, is_inifite(a));

Mt.from_pair_suites("Gpr_1716_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  a ,
  b ,
  is_inifite ,
}
/*  Not a pure module */
