// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";

function on1(foo, $$event) {
  foo.on($$event.NAME, $$event.VAL);
}

function on2(foo, h, $$event) {
  foo.on(Curry._1(h, $$event).NAME, Curry._1(h, $$event).VAL);
}

export {
  on1 ,
  on2 ,
}
/* No side effect */
