// Generated by Melange

import * as $$Buffer from "melange/jscomp/stdlib-412/stdlib_modules/buffer.mjs";

var foo = $$Buffer.contents;

function bar(str) {
  return Buffer.from(str);
}

export {
  foo ,
  bar ,
}
/* No side effect */
