// Generated by Melange

import * as Caml_obj from "melange/lib/es6/caml_obj.mjs";
import * as Caml_option from "melange/lib/es6/caml_option.mjs";

if (!Caml_obj.caml_equal(Caml_option.nullable_to_opt(""), "")) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "gpr_974_test.ml",
          5,
          4
        ],
        Error: new Error()
      };
}

if (!Caml_obj.caml_equal(Caml_option.undefined_to_opt(""), "")) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "gpr_974_test.ml",
          6,
          4
        ],
        Error: new Error()
      };
}

if (!Caml_obj.caml_equal(Caml_option.null_to_opt(""), "")) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "gpr_974_test.ml",
          7,
          4
        ],
        Error: new Error()
      };
}

export {
  
}
/*  Not a pure module */
