// Generated by Melange

import * as Belt_Array from "melange.runtime-others/jscomp/others/belt_Array.js";

var b = Belt_Array.eq([
      1,
      2,
      3
    ], [
      1,
      2,
      3
    ], (function (prim0, prim1) {
        return prim0 === prim1;
      }));

export {
  b ,
}
/* b Not a pure module */
