// Generated by Melange

import * as Mt from "./mt.js";
import * as Caml_option from "melange/lib/es6/caml_option.mjs";
import * as Gpr_3566_test from "./gpr_3566_test.js";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

var H = Gpr_3566_test.Test({});

eq("File \"gpr_3566_drive_test.ml\", line 8, characters 5-12", H.b, true);

var Caml_option$1 = {};

function f(x) {
  return Caml_option.some(x);
}

Mt.from_pair_suites("gpr_3566_drive_test.ml", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  H ,
  Caml_option$1 as Caml_option,
  f ,
}
/* H Not a pure module */
