// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";
import * as Caml_oo_curry from "melange/lib/es6/caml_oo_curry.mjs";

function h1(u) {
  return u.p;
}

function h2(u) {
  return u.m(1, 2);
}

function h3(u) {
  var f = u.hi;
  return Curry._2(f, 1, 2);
}

function h4(u) {
  return u.hi(1, 2);
}

function h5(u) {
  u.hi = 3;
}

function h6(u) {
  return Caml_oo_curry.js1(112, 1, u);
}

function h7(u) {
  return Caml_oo_curry.js1(109, 2, u)(1, 2);
}

function h8(u) {
  var f = Caml_oo_curry.js1(23297, 3, u);
  return Curry._2(f, 1, 2);
}

function chain_g(h) {
  var tmp = Caml_oo_curry.js1(120, 4, h);
  var tmp$1 = Caml_oo_curry.js1(121, 5, tmp);
  return Caml_oo_curry.js1(122, 6, tmp$1);
}

export {
  h1 ,
  h2 ,
  h3 ,
  h4 ,
  h5 ,
  h6 ,
  h7 ,
  h8 ,
  chain_g ,
}
/* No side effect */
