// Generated by Melange


var hh = {
  hi: 30,
  lo: 20
};

var v = {
  hi: 32,
  lo: 3
};

var vv = {
  hi: 3,
  lo: 3,
  width: 3
};

var u = v.hi;

var uu = v.width;

export {
  hh ,
  v ,
  vv ,
  u ,
  uu ,
}
/*  Not a pure module */
