// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Curry from "melange/lib/es6/curry.mjs";
import * as $$String from "melange/jscomp/stdlib-412/stdlib_modules/string.mjs";
import * as Filename from "melange/jscomp/stdlib-412/stdlib_modules/filename.mjs";
import * as Caml_string from "melange/lib/es6/caml_string.mjs";

function generic_basename(is_dir_sep, current_dir_name, name) {
  if (name === "") {
    return current_dir_name;
  } else {
    var _n = name.length - 1 | 0;
    while(true) {
      var n = _n;
      if (n < 0) {
        return $$String.sub(name, 0, 1);
      }
      if (!Curry._2(is_dir_sep, name, n)) {
        var _n$1 = n;
        var p = n + 1 | 0;
        while(true) {
          var n$1 = _n$1;
          if (n$1 < 0) {
            return $$String.sub(name, 0, p);
          }
          if (Curry._2(is_dir_sep, name, n$1)) {
            return $$String.sub(name, n$1 + 1 | 0, (p - n$1 | 0) - 1 | 0);
          }
          _n$1 = n$1 - 1 | 0;
          continue ;
        };
      }
      _n = n - 1 | 0;
      continue ;
    };
  }
}

function basename(param) {
  return generic_basename((function (s, i) {
                return Caml_string.get(s, i) === /* '/' */47;
              }), Filename.current_dir_name, param);
}

var suites_0 = [
  "basename",
  (function (param) {
      return {
              TAG: /* Eq */0,
              _0: basename("b/c/a.b"),
              _1: "a.b"
            };
    })
];

var suites = {
  hd: suites_0,
  tl: /* [] */0
};

Mt.from_pair_suites("Inline_regression_test", suites);

export {
  generic_basename ,
  basename ,
  suites ,
}
/*  Not a pure module */
