// Generated by Melange


var N = {};

console.log([
      3e-6,
      3e-6
    ]);

var x = true;

function N1(funarg) {
  return {};
}

var h = "hello";

var hh = "hellohello";

export {
  x ,
  N ,
  N1 ,
  h ,
  hh ,
}
/*  Not a pure module */
