// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Int64 from "melange/jscomp/stdlib-412/stdlib_modules/int64.mjs";
import * as Caml_int64 from "melange/lib/es6/caml_int64.mjs";
import * as Inline_const from "./inline_const.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

var H = {};

var f = "hello";

var f1 = "a";

var f2 = "中文";

var f3 = "中文";

var f4 = "中文";

eq("File \"inline_const_test.ml\", line 29, characters 5-12", f, "hello");

eq("File \"inline_const_test.ml\", line 30, characters 5-12", f1, "a");

eq("File \"inline_const_test.ml\", line 31, characters 5-12", f2, "中文");

eq("File \"inline_const_test.ml\", line 32, characters 5-12", f3, "中文");

eq("File \"inline_const_test.ml\", line 33, characters 5-12", f4, "中文");

eq("File \"inline_const_test.ml\", line 34, characters 5-12", true, true);

eq("File \"inline_const_test.ml\", line 35, characters 5-12", 1, 1);

eq("File \"inline_const_test.ml\", line 36, characters 5-12", 3e-6, 0.000003);

var h = Caml_int64.add(Caml_int64.add([
          0,
          100
        ], Int64.one), Caml_int64.one);

Mt.from_pair_suites("File \"inline_const_test.ml\", line 43, characters 22-29", suites.contents);

var f5 = true;

var f6 = 1;

var f7 = 3e-6;

export {
  suites ,
  test_id ,
  eq ,
  H ,
  f ,
  f1 ,
  f2 ,
  f3 ,
  f4 ,
  f5 ,
  f6 ,
  f7 ,
  h ,
}
/*  Not a pure module */
