// Generated by Melange


function f(x) {
  return x + 3 | 0;
}

function M(S) {
  var f = function (x) {
    return x;
  };
  return {
          f: f
        };
}

function fff(param, param$1) {
  return 3;
}

export {
  f ,
  M ,
  fff ,
}
/* No side effect */
