// Generated by Melange

import * as Mt from "./mt.mjs";
import * as Caml_int32 from "melange/lib/es6/caml_int32.mjs";

function u(param) {
  var n;
  try {
    n = 3;
  }
  catch (exn){
    return 42;
  }
  return Caml_int32.div(3, 0);
}

Mt.from_pair_suites("Jsoo_400_test", {
      hd: [
        "File \"jsoo_400_test.ml\", line 8, characters 3-10",
        (function (param) {
            return {
                    TAG: /* ThrowAny */7,
                    _0: (function (param) {
                        u(undefined);
                      })
                  };
          })
      ],
      tl: /* [] */0
    });

export {
  u ,
}
/*  Not a pure module */
