// Generated by Melange

import * as Vscode from "vscode";
import * as SomeEs6Module from "some-es6-module";
import SomeEs6Module$1 from "some-es6-module";
import OmeEs6Module from "./ome-es6-module";
import * as OmeEs6Module$1 from "./ome-es6-module";

var $$default = SomeEs6Module$1;

var default2 = SomeEs6Module.default2;

var oefault = OmeEs6Module;

var oefault2 = OmeEs6Module$1.default2;

var $$window = Vscode.window;

function mk($$window, $$default) {
  return {
          window: $$window,
          default: $$default
        };
}

function mk2($$window, $$default) {
  return {
          hd: {
            window: $$window,
            default: $$default
          },
          tl: /* [] */0
        };
}

function des(v) {
  return {
          window: v.window,
          default: v.default
        };
}

var test = {
  case: 3,
  window: 3
};

function u(param) {
  return $$window.switch();
}

var $$case = 3;

export {
  $$default ,
  $$default as default,
  default2 ,
  oefault ,
  oefault2 ,
  $$window ,
  mk ,
  mk2 ,
  des ,
  $$case ,
  test ,
  u ,
}
/* default Not a pure module */
