// Generated by Melange

import * as Caml_format from "melange/lib/es6/caml_format.mjs";

function f(x) {
  return x;
}

function u(x, y) {
  return x + Caml_format.caml_int_of_string(y) | 0;
}

function u1(f) {
  console.log(f(2, "x"));
  console.log(f(2, "x"));
}

function h(unit) {
  return 3;
}

var a = u1(u);

export {
  f ,
  u ,
  u1 ,
  h ,
  a ,
}
/* a Not a pure module */
