// Generated by Melange

import * as Caml_oo_curry from "melange/lib/es6/caml_oo_curry.mjs";

function f(x) {
  x.height = 3;
}

function h(x) {
  return Caml_oo_curry.js1(38537191, 1, x);
}

export {
  f ,
  h ,
}
/* No side effect */
