// Generated by Melange

import * as Format from "melange/jscomp/stdlib-412/stdlib_modules/format.js";

function write_runtime_coverage(channel) {
  Format.formatter_of_out_channel(channel);
}

export {
  write_runtime_coverage ,
}
/* Format Not a pure module */
