// Generated by Melange

import * as Mt from "./mt.mjs";
import * as JoinClasses from "./joinClasses";
import * as Caml_splice_call from "melange/lib/es6/caml_splice_call.mjs";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, param) {
  var y = param[1];
  var x = param[0];
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

function joinClasses(prim) {
  return Caml_splice_call.spliceApply(JoinClasses, [prim]);
}

var a = JoinClasses(1, 2, 3);

var pair = [
  a,
  6
];

console.log(pair);

eq("File \"module_splice_test.ml\", line 21, characters 5-12", pair);

Mt.from_pair_suites("Module_splice_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  joinClasses ,
  a ,
}
/* a Not a pure module */
