// Generated by Melange


var structural_obj = {
  x: {
    y: {
      z: 3
    }
  }
};

var f_record = {
  x: {
    y: {
      z: 3
    }
  }
};

export {
  structural_obj ,
  f_record ,
}
/* No side effect */
