// Generated by Melange


function f(param) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "noassert.ml",
          5,
          11
        ],
        Error: new Error()
      };
}

function h(param) {
  
}

export {
  f ,
  h ,
}
/* No side effect */
