// Generated by Melange


var a = {
  x: 3,
  y: [1]
};

var b = {
  x: 3,
  y: [1],
  z: 3,
  u: (function (x, y) {
      return x + y | 0;
    })
};

function f(obj) {
  return obj.x + obj.y.length | 0;
}

function h(obj) {
  return obj.u(1, 2);
}

var u = f(a);

var v = f(b);

var vv = h(b);

export {
  a ,
  b ,
  f ,
  h ,
  u ,
  v ,
  vv ,
}
/* u Not a pure module */
