// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";
import * as Belt_Array from "melange.runtime-others/jscomp/others/belt_Array.mjs";

var N = {};

function forEach(xs, f) {
  Belt_Array.forEach(xs, (function (x) {
          Curry._1(f.i, x);
        }));
}

var Y = {
  forEach: forEach
};

function f(X) {
  return function (xs) {
    X.forEach(xs, {
          i: (function (x) {
              console.log(x.x);
            })
        });
  };
}

function g(X) {
  return function (xs) {
    Belt_Array.forEach(xs, (function (x) {
            console.log(x);
          }));
  };
}

var g_result = g(Y)([]);

export {
  N ,
  Y ,
  f ,
  g ,
  g_result ,
}
/* g_result Not a pure module */
