// Generated by Melange


var revData = {"x":"a","b":"b"};

var data = {"a":"x","b":"b"};

function tToJs(x) {
  return data[x];
}

function vFromJsOpt(s) {
  return revData[s];
}

function vFromJs(s) {
  return revData[s];
}

export {
  revData ,
  data ,
  tToJs ,
  vFromJsOpt ,
  vFromJs ,
}
/* No side effect */
