// Generated by Melange


function map(f, param) {
  if (!param) {
    return /* [] */0;
  }
  var r = f(param.hd);
  return {
          hd: r,
          tl: map(f, param.tl)
        };
}

export {
  map ,
}
/* No side effect */
