// Generated by Melange

import * as Mt from "./mt.js";

var suites = {
  contents: /* [] */0
};

var test_id = {
  contents: 0
};

function eq(loc, x, y) {
  test_id.contents = test_id.contents + 1 | 0;
  suites.contents = {
    hd: [
      loc + (" id " + String(test_id.contents)),
      (function (param) {
          return {
                  TAG: /* Eq */0,
                  _0: x,
                  _1: y
                };
        })
    ],
    tl: suites.contents
  };
}

var u = 3;

function nullary() {
  return 3;
}

function unary(a) {
  return a + 3 | 0;
}

var xx = unary(3);

eq("File \"ppx_apply_test.ml\", line 17, characters 5-12", u, 3);

function h(a) {
  return xx(a);
}

Mt.from_pair_suites("Ppx_apply_test", suites.contents);

export {
  suites ,
  test_id ,
  eq ,
  u ,
  nullary ,
  unary ,
  xx ,
  h ,
}
/* u Not a pure module */
