// Generated by Melange

import * as SysBluebird from "sys-bluebird";

function f(p) {
  return p.catch(3);
}

var p = new SysBluebird.Promise();

p.then(function (x) {
        return x + 3 | 0;
      }).catch(function (reason) {
      return reason;
    });

var u = {
  then: 3,
  catch: 32
};

var uu = {
  "'x": 3
};

var hh = uu["'x"];

export {
  f ,
  u ,
  uu ,
  hh ,
}
/* p Not a pure module */
