// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";

function mk(fn) {
  return Curry._1(fn, undefined);
}

(((_)=> console.log('should works'))(undefined));

console.log((function () {
          return 1;
        })());

export {
  mk ,
}
/*  Not a pure module */
