// Generated by Melange
/**
 * copyright 
*/
// hello

import * as List from "melange/jscomp/stdlib-412/stdlib_modules/list.mjs";

var x0 = null;

var x2 = "荷兰";

var x3 = /ghoghos/;

/**
 * copyright
*/

function f(x) {
  //eslint-disable
  /*hgosgh */
  return x;
}

var hh = List.length;

export {
  x0 ,
  x2 ,
  x3 ,
  hh ,
  f ,
}
/* No side effect */
