// Generated by Melange

import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var A = /* @__PURE__ */Caml_exceptions.create("Rebind_module.A");

var AA = /* @__PURE__ */Caml_exceptions.create("Rebind_module.AA");

export {
  A ,
  AA ,
}
/* No side effect */
