// Generated by Melange

import * as $$Set from "melange/jscomp/stdlib-412/stdlib_modules/set.js";
import * as Caml from "melange/lib/es6/caml.mjs";
import * as Curry from "melange/lib/es6/curry.mjs";

function compare(t1, t2) {
  if (t1.TAG === /* Leaf */0) {
    if (t2.TAG === /* Leaf */0) {
      return Caml.caml_string_compare(t1._0, t2._0);
    } else {
      return 1;
    }
  } else if (t2.TAG === /* Leaf */0) {
    return -1;
  } else {
    return Curry._2(ASet.compare, t1._0, t2._0);
  }
}

var A = {
  compare: compare
};

var ASet = $$Set.Make(A);

var X0 = {};

var Y0 = {};

function f(x) {
  return x + 1 | 0;
}

var X1 = {
  f: f
};

function f$1(x) {
  return x + 2 | 0;
}

var Y1 = {
  f: f$1
};

var X;

export {
  A ,
  ASet ,
  X ,
  X0 ,
  Y0 ,
  X1 ,
  Y1 ,
}
/* ASet Not a pure module */
