// Generated by Melange

import * as FileJs from "./File.js";

var foo = FileJs.foo;

function foo2(prim) {
  return FileJs.foo2(prim);
}

var bar = foo;

export {
  foo ,
  foo2 ,
  bar ,
}
/* foo Not a pure module */
