// Generated by Melange


function f0(x) {
  return x;
}

function f1(x) {
  return 2;
}

function f3(x) {
  if (x !== undefined) {
    return x;
  } else {
    return /* A */0;
  }
}

var v0;

export {
  f0 ,
  f1 ,
  f3 ,
  v0 ,
}
/* No side effect */
