// Generated by Melange

import * as Mt from "./mt.mjs";

Mt.from_pair_suites("string_get_set_test.ml", {
      hd: [
        "File \"string_get_set_test.ml\", line 6, characters 4-11",
        (function (param) {
            return {
                    TAG: /* Eq */0,
                    _0: /* 'h' */104,
                    _1: /* 'h' */104
                  };
          })
      ],
      tl: /* [] */0
    });

export {
  
}
/*  Not a pure module */
