// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";
import * as Submodule from "./submodule.mjs";

var a0 = Submodule.A0.a0(1, 2);

var a1 = Curry._2(Submodule.A0.A1.a1, 1, 2);

var a2 = Curry._2(Submodule.A0.A1.A2.a2, 1, 2);

var a3 = Curry._2(Submodule.A0.A1.A2.A3.a3, 1, 2);

var a4 = Curry._2(Submodule.A0.A1.A2.A3.A4.a4, 1, 2);

export {
  a0 ,
  a1 ,
  a2 ,
  a3 ,
  a4 ,
}
/* a0 Not a pure module */
