// Generated by Melange


var node_modules = "node_modules";

var node_modules_length = 12;

var bsconfig_json = "bsconfig.json";

export {
  node_modules ,
  node_modules_length ,
  bsconfig_json ,
}
/* No side effect */
