// Generated by Melange

import * as Sys from "melange/jscomp/stdlib-412/stdlib_modules/sys.mjs";

var os_version;

switch (Sys.os_type) {
  case "Cygwin" :
      os_version = 2;
      break;
  case "Unix" :
      os_version = 1;
      break;
  default:
    os_version = 3;
}

export {
  os_version ,
}
/* os_version Not a pure module */
