// Generated by Melange

import * as Stdlib from "melange.stdlib/jscomp/stdlib-412/stdlib.mjs";
import * as Test_common from "./test_common.mjs";
import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var Local = /* @__PURE__ */Caml_exceptions.create("Test_exception.Local");

function f(param) {
  throw {
        RE_EXN_ID: Local,
        _1: 3,
        Error: new Error()
      };
}

function g(param) {
  throw {
        RE_EXN_ID: Stdlib.Not_found,
        Error: new Error()
      };
}

function h(param) {
  throw {
        RE_EXN_ID: Test_common.U,
        _1: 3,
        Error: new Error()
      };
}

function x(param) {
  throw {
        RE_EXN_ID: Test_common.H,
        Error: new Error()
      };
}

function xx(param) {
  throw {
        RE_EXN_ID: Stdlib.Invalid_argument,
        _1: "x",
        Error: new Error()
      };
}

var Nullary = /* @__PURE__ */Caml_exceptions.create("Test_exception.Nullary");

var a = {
  RE_EXN_ID: Nullary
};

export {
  Local ,
  f ,
  g ,
  h ,
  x ,
  xx ,
  Nullary ,
  a ,
}
/* No side effect */
