// Generated by Melange

import * as $$Array from "melange/jscomp/stdlib-412/stdlib_modules/array.mjs";
import * as Caml_array from "melange/lib/es6/caml_array.mjs";

function f(a, b, param) {
  return a + b | 0;
}

function f2(a) {
  return function (param) {
    return a + 1 | 0;
  };
}

var a = String(3);

var b = 101;

var arr = $$Array.init(2, (function (param) {
        return 0;
      }));

for(var i = 0; i <= 1; ++i){
  Caml_array.set(arr, i, i + 1 | 0);
}

console.log([
      a,
      b,
      arr
    ]);

var c = arr;

export {
  f ,
  f2 ,
  a ,
  b ,
  c ,
}
/* a Not a pure module */
