// Generated by Melange

import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var U = /* @__PURE__ */Caml_exceptions.create("Test_common.U");

var H = /* @__PURE__ */Caml_exceptions.create("Test_common.H");

export {
  U ,
  H ,
}
/* No side effect */
