// Generated by Melange

import * as List from "melange/jscomp/stdlib-412/stdlib_modules/list.js";
import * as Curry from "melange/lib/es6/curry.mjs";

function fib(n) {
  if (n === 2 || n === 1) {
    return 1;
  } else {
    return fib(n - 1 | 0) + fib(n - 2 | 0) | 0;
  }
}

function cons(x, y) {
  return /* Cons */{
          _0: x,
          _1: y
        };
}

function map(f, param) {
  if (param) {
    return /* Cons */{
            _0: Curry._1(f, param._0),
            _1: map(f, param._1)
          };
  } else {
    return /* Nil */0;
  }
}

function sum(n) {
  var v = 0;
  for(var i = 0; i <= n; ++i){
    v = v + i | 0;
  }
  return v;
}

function f(x, y, z) {
  return (x + y | 0) + z | 0;
}

function g(x, y) {
  var u = x + y | 0;
  return function (z) {
    return u + z | 0;
  };
}

function g1(x, y) {
  var u = x + y | 0;
  return function (xx, yy) {
    return (xx + yy | 0) + u | 0;
  };
}

var u = 8;

var x = u + 6 | 0;

var u$1 = 7;

function v(param) {
  return (6 + param | 0) + u$1 | 0;
}

var nil = /* Nil */0;

var len = List.length;

export {
  fib ,
  nil ,
  cons ,
  map ,
  sum ,
  len ,
  f ,
  g ,
  g1 ,
  x ,
  v ,
}
/* No side effect */
