// Generated by Melange

import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var A = /* @__PURE__ */Caml_exceptions.create("Test_exception_escape.N.A");

var f;

try {
  throw {
        RE_EXN_ID: A,
        _1: 3,
        Error: new Error()
      };
}
catch (exn){
  f = 3;
}

var N = {
  f: f
};

export {
  N ,
}
/* f Not a pure module */
