// Generated by Melange

import * as $$Array from "melange/jscomp/stdlib-412/stdlib_modules/array.mjs";

var const_v = $$Array.append([
      1,
      2
    ], [3]);

export {
  const_v ,
}
/* const_v Not a pure module */
