// Generated by Melange

import * as List from "melange/jscomp/stdlib-412/stdlib_modules/list.js";
import * as Filename from "melange/jscomp/stdlib-412/stdlib_modules/filename.js";

var u = Filename.chop_extension;

var v = List.length;

export {
  u ,
  v ,
}
/* Filename Not a pure module */
