// Generated by Melange

import * as Caml_bytes from "melange/lib/es6/caml_bytes.mjs";

var f = Caml_bytes.bytes_to_string;

var ff = Caml_bytes.bytes_to_string;

export {
  f ,
  ff ,
}
/* No side effect */
