// Generated by Melange

import * as $$String from "melange/jscomp/stdlib-412/stdlib_modules/string.js";

function v(u) {
  t({
        compare: $$String.compare
      });
}

function u(v) {
  return v;
}

var s = $$String;

export {
  v ,
  u ,
  s ,
}
/* No side effect */
