// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";

var v = {
  contents: 0
};

function gen(param) {
  v.contents = v.contents + 1 | 0;
  return v.contents;
}

var h = {
  contents: 0
};

var a = 0;

var c = {
  contents: 0
};

var not_real_escape = a;

function real_escape(f, v) {
  return Curry._1(f, c);
}

var u = h;

export {
  u ,
  gen ,
  not_real_escape ,
  real_escape ,
}
/* No side effect */
