// Generated by Melange

import * as Caml_array from "melange/lib/es6/caml_array.mjs";

function g(x) {
  return [
          3,
          x
        ];
}

function ff(v, u) {
  return {
          v: v,
          u: u
        };
}

function fff(vv, uu) {
  return {
          vv: vv,
          uu: uu
        };
}

function a(x) {
  return Caml_array.get(x, 0);
}

function aa(x) {
  return Caml_array.get(x, 0);
}

function aaa(x) {
  return x.v;
}

function aaaa(x) {
  return x.vv;
}

function f(x) {
  for(var i = 0; i <= 10; ++i){
    Caml_array.set(x, i, i);
  }
}

export {
  g ,
  ff ,
  fff ,
  a ,
  aa ,
  aaa ,
  aaaa ,
  f ,
}
/* No side effect */
