// Generated by Melange

import * as Stdlib from "melange.stdlib/jscomp/stdlib-412/stdlib.mjs";
import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var Scan_failure = /* @__PURE__ */Caml_exceptions.create("Test_static_catch_ident.Scan_failure");

function scanf_bad_input(ib, x) {
  var s;
  if (x.RE_EXN_ID === Scan_failure || x.RE_EXN_ID === Stdlib.Failure) {
    s = x._1;
  } else {
    throw x;
  }
  for(var i = 0; i <= 100; ++i){
    console.log(s);
    console.log("don't inlinie");
  }
}

export {
  Scan_failure ,
  scanf_bad_input ,
}
/* No side effect */
