// Generated by Melange

import * as Caml_exceptions from "melange/lib/es6/caml_exceptions.mjs";

var Custom_inline = /* @__PURE__ */Caml_exceptions.create("Test_literal.Custom_inline");

var v = {
  RE_EXN_ID: Custom_inline,
  _1: 1,
  _2: 2
};

var vv = [
  1,
  2,
  3
];

var long_v = [
  1,
  2,
  3,
  4,
  5,
  6
];

var long_int_v = [
  1,
  2,
  3,
  4,
  5,
  6
];

var short_int_v = [1];

var empty = [];

export {
  Custom_inline ,
  v ,
  vv ,
  long_v ,
  long_int_v ,
  short_int_v ,
  empty ,
}
/* No side effect */
