// Generated by Melange

import * as $$Array from "melange/jscomp/stdlib-412/stdlib_modules/array.mjs";
import * as Caml_array from "melange/lib/es6/caml_array.mjs";

var v = Caml_array.make(6, 5);

Caml_array.make_float(30);

var h = $$Array.sub(v, 0, 2);

var hhh = $$Array.append([
      1,
      2,
      3,
      4
    ], [
      1,
      2,
      3,
      5
    ]);

var u = Caml_array.concat({
      hd: [
        1,
        2
      ],
      tl: {
        hd: [
          2,
          3
        ],
        tl: {
          hd: [
            3,
            4
          ],
          tl: /* [] */0
        }
      }
    });

var hh = $$Array.blit;

export {
  v ,
  h ,
  hh ,
  hhh ,
  u ,
}
/*  Not a pure module */
