// Generated by Melange

import * as Caml_option from "melange/lib/es6/caml_option.mjs";

function v(displayName, param) {
  var tmp = {
    test: 3,
    config: 3,
    hi: "ghos"
  };
  if (displayName !== undefined) {
    tmp.displayName = Caml_option.valFromOption(displayName);
  }
  return tmp;
}

var v2 = {
  test: 3,
  config: 3,
  hi: "ghos"
};

var v3 = {
  displayName: "display",
  test: 3,
  config: 3,
  hi: "ghos"
};

function u(x) {
  return x;
}

function ff(x) {
  return x;
}

function fff(x) {
  return x;
}

function f(x) {
  return x;
}

export {
  v ,
  v2 ,
  v3 ,
  u ,
  ff ,
  fff ,
  f ,
}
/* No side effect */
