// Generated by Melange

import * as $$Array from "melange/jscomp/stdlib-412/stdlib_modules/array.js";

var v = {
  contents: 32
};

v.contents = 0;

var N = {
  a: 3,
  v: v
};

var v$1 = {
  contents: 32
};

var NN = {
  a: 3,
  v: v$1
};

var make_float = $$Array.make_float;

var init = $$Array.init;

var make_matrix = $$Array.make_matrix;

var create_matrix = $$Array.create_matrix;

var append = $$Array.append;

var concat = $$Array.concat;

var sub = $$Array.sub;

var copy = $$Array.copy;

var fill = $$Array.fill;

var blit = $$Array.blit;

var to_list = $$Array.to_list;

var of_list = $$Array.of_list;

var iter = $$Array.iter;

var iteri = $$Array.iteri;

var map = $$Array.map;

var mapi = $$Array.mapi;

var fold_left = $$Array.fold_left;

var fold_left_map = $$Array.fold_left_map;

var fold_right = $$Array.fold_right;

var iter2 = $$Array.iter2;

var map2 = $$Array.map2;

var for_all = $$Array.for_all;

var exists = $$Array.exists;

var for_all2 = $$Array.for_all2;

var exists2 = $$Array.exists2;

var mem = $$Array.mem;

var memq = $$Array.memq;

var find_opt = $$Array.find_opt;

var find_map = $$Array.find_map;

var split = $$Array.split;

var combine = $$Array.combine;

var sort = $$Array.sort;

var stable_sort = $$Array.stable_sort;

var fast_sort = $$Array.fast_sort;

var to_seq = $$Array.to_seq;

var to_seqi = $$Array.to_seqi;

var of_seq = $$Array.of_seq;

var Floatarray = $$Array.Floatarray;

var a = 3;

export {
  make_float ,
  init ,
  make_matrix ,
  create_matrix ,
  append ,
  concat ,
  sub ,
  copy ,
  fill ,
  blit ,
  to_list ,
  of_list ,
  iter ,
  iteri ,
  map ,
  mapi ,
  fold_left ,
  fold_left_map ,
  fold_right ,
  iter2 ,
  map2 ,
  for_all ,
  exists ,
  for_all2 ,
  exists2 ,
  mem ,
  memq ,
  find_opt ,
  find_map ,
  split ,
  combine ,
  sort ,
  stable_sort ,
  fast_sort ,
  to_seq ,
  to_seqi ,
  of_seq ,
  Floatarray ,
  N ,
  NN ,
  a ,
  v ,
}
/*  Not a pure module */
