// Generated by Melange

import * as Curry from "melange/lib/es6/curry.mjs";

var v = {
  contents: 0
};

function reset(param) {
  v.contents = 0;
}

function incr(param) {
  v.contents = v.contents + 1 | 0;
}

var vv = {
  contents: 0
};

function reset2(param) {
  vv.contents = 0;
}

function incr2(param) {
  v.contents = v.contents + 1 | 0;
}

function f(a, b, d, e) {
  var h = Curry._1(a, b);
  var u = Curry._1(d, h);
  var v = Curry._1(e, h);
  return u + v | 0;
}

function kf(cb, v) {
  Curry._1(cb, v);
  return v + v | 0;
}

function ikf(v) {
  return kf((function (prim) {
                
              }), v);
}

export {
  v ,
  reset ,
  incr ,
  reset2 ,
  incr2 ,
  f ,
  kf ,
  ikf ,
}
/* No side effect */
