// Generated by Melange


function f(obj) {
  if (typeof obj === "function") {
    return ;
  }
  var size = obj.length;
  if (size !== undefined) {
    console.log(size);
    return ;
  }
  
}

export {
  f ,
}
/* No side effect */
