// Generated by Melange

import * as Fs from "fs";

function test(path) {
  Fs.watch(path, {
            recursive: true
          }).on("change", (function ($$event, string_buffer) {
            console.log([
                  $$event,
                  string_buffer
                ]);
          })).close();
}

export {
  test ,
}
/* fs Not a pure module */
