// Generated by Melange

import * as List from "melange/jscomp/stdlib-412/stdlib_modules/list.js";
import * as List$1 from "List";
import * as List$2 from "reactV";
import * as List$3 from "reactX";
import * as Local from "./local";
import * as WebpackConfigJs from "../../../webpack.config.js";
import * as WebpackMiddlewareConfigJs from "../../../webpack.middleware.config.js";

var configx = WebpackConfigJs;

var WebpackConfig = {
  configx: configx
};

var configx$1 = WebpackMiddlewareConfigJs;

var WebpackDevMiddlewareConfig = {
  configx: configx$1
};

function configX(prim) {
  return WebpackMiddlewareConfigJs.configX();
}

function configX$1(prim) {
  return WebpackConfigJs.configX();
}

var U = {
  configX: configX$1
};

var A = {};

var B = {};

function f(param) {
  return [
          (function (prim) {
              List$3.ff();
            }),
          (function (prim) {
              List$3.ff2();
            }),
          (function (prim) {
              List$2.ff();
            }),
          (function (prim) {
              List$2.ff2();
            })
        ];
}

List$1.xx();

List.length({
      hd: 1,
      tl: {
        hd: 2,
        tl: /* [] */0
      }
    });

List.length(/* [] */0);

function ff(prim) {
  return Local.ff();
}

export {
  WebpackConfig ,
  WebpackDevMiddlewareConfig ,
  configX ,
  U ,
  A ,
  B ,
  f ,
  ff ,
}
/* configx Not a pure module */
