Demonstrate dune produces JS files corresponding to the original file name

  $ . ../setup.sh
  $ dune build ./libB/.b.objs/melange/b.cmj

  $ ls _build/default/libA/.a.objs/melange
  a.cmi
  a.cmj
  a.cmt
  a__.cmi
  a__.cmj
  a__.cmt
  a__Other.cmi
  a__Other.cmj
  a__Other.cmt

  $ ls _build/default/libB/.b.objs/melange
  b.cmi
  b.cmj
  b.cmt

  $ dune build @melange-dist

  $ cat _build/default/dist/libA/a.js
  // Generated by Melange
  
  import * as A__Other from "./other.js";
  
  const x = A__Other.t;
  
  const t = 1;
  
  export {
    x,
    t,
  }
  /* No side effect */
