  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > console.log(ocaml.compileML("let t = Js.Vector.length"));
  > EOF

  $ node input.js
  File "_none_", line 1, characters 8-24:
  Alert deprecated: module Js.Vector
  Use Belt.Array instead
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'function t(prim) {\n' +
      '  return prim.length;\n' +
      '}\n' +
      '\n' +
      'export {\n' +
      '  t ,\n' +
      '}\n' +
      '/* No side effect */\n',
    warnings: [],
    type_hints: [
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: "'a Js.Vector.t -> int"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: "'a Js.Vector.t -> int"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'binding',
        hint: "'a Js.Vector.t -> int"
      }
    ]
  }
