  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/playground/mel_playground.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/playground/melange-cmijs.js');
  > console.log(ocaml.compileML("let foo = Belt.List.map"));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      'import * as Belt__Belt_List from "melange.belt/belt_List.js";\n' +
      '\n' +
      'var foo = Belt__Belt_List.map;\n' +
      '\n' +
      'export {\n' +
      '  foo ,\n' +
      '}\n' +
      '/* No side effect */\n',
    warnings: [],
    type_hints: [
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: "'a Belt.List.t -> ('a -> 'b) -> 'b Belt.List.t"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: "'a Belt.List.t -> ('a -> 'b) -> 'b Belt.List.t"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'binding',
        hint: "'a Belt.List.t -> ('a -> 'b) -> 'b Belt.List.t"
      }
    ]
  }
