  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > console.log(ocaml.compileML("let t = 1"));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'var t = 1;\n' +
      '\n' +
      'export {\n' +
      '  t ,\n' +
      '}\n' +
      '/* No side effect */\n',
    type_hints: [
      { start: [Object], end: [Object], kind: 'expression', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'int'
      },
      { start: [Object], end: [Object], kind: 'binding', hint: 'int' }
    ]
  }
