  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/playground/mel_playground.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/playground/melange-cmijs.js');
  > console.log(ocaml.compileML("external imul : int -> int -> int = \"imul\"[@@mel.scope \"Math\"]\nlet res = imul 1 2"));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'const res = Math.imul(1, 2);\n' +
      '\n' +
      'export {\n' +
      '  res ,\n' +
      '}\n' +
      '/* res Not a pure module */\n',
    warnings: [],
    type_hints: [
      { start: [Object], end: [Object], kind: 'expression', hint: 'int' },
      { start: [Object], end: [Object], kind: 'expression', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'int -> int -> int'
      },
      { start: [Object], end: [Object], kind: 'expression', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'int'
      },
      { start: [Object], end: [Object], kind: 'binding', hint: 'int' },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'int -> int'
      },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'int -> int -> int'
      }
    ]
  }
