  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > console.log(ocaml.compileML("type t = Dom.element"));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      "/* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */\n",
    type_hints: [
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'Dom.element'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'type_declaration',
        hint: 'type t = Dom.element'
      }
    ]
  }
