  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > console.log(ocaml.compileML(\`type person = {
  >   name: string ;
  >   age: int
  > }[@@deriving abstract]
  > 
  > let person1: person = person ~name:"joe" ~age:10\`));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'var person1 = {\n' +
      '  name: "joe",\n' +
      '  age: 10\n' +
      '};\n' +
      '\n' +
      'export {\n' +
      '  person1 ,\n' +
      '}\n' +
      '/* No side effect */\n',
    warnings: [
      {
        js_warning_error_msg: 'Line 6, 22:\n' +
          '  Alert: deprecated person\n' +
          'The `@deriving abstract` payload is deprecated, use `@deriving dynamicKeys` instead.',
        row: 5,
        column: 22,
        endRow: 5,
        endColumn: 28,
        text: 'person\n' +
          'The `@deriving abstract` payload is deprecated, use `@deriving dynamicKeys` instead.',
        type: 'alert'
      }
    ],
    type_hints: [
      { start: [Object], end: [Object], kind: 'expression', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'name:string -> age:int -> person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'person'
      },
      { start: [Object], end: [Object], kind: 'binding', hint: 'person' },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person -> int'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person -> string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person'
      },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'age:int -> person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'name:string -> age:int -> person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'unit'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'person'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'person -> unit'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'person -> unit'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'binding',
        hint: 'person -> unit'
      },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      { start: [Object], end: [Object], kind: 'core_type', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'type_declaration',
        hint: 'type person = { name : string; age : int; }'
      }
    ]
  }
