  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > console.log(ocaml.compileML(\`let john = [%mel.obj { name = "john"; age = 99 }] let t = john##name\`));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'var john = {\n' +
      '  name: "john",\n' +
      '  age: 99\n' +
      '};\n' +
      '\n' +
      'var t = john.name;\n' +
      '\n' +
      'export {\n' +
      '  john ,\n' +
      '  t ,\n' +
      '}\n' +
      '/* t Not a pure module */\n',
    type_hints: [
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: '< age : int; name : string > Js.t'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: '< age : int; name : string > Js.t Js__.Js_internal.t ->\n' +
          '< age : int; name : string > Js.t'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: '< age : int; name : string > Js.t'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: 'string'
      },
      { start: [Object], end: [Object], kind: 'binding', hint: 'string' },
      { start: [Object], end: [Object], kind: 'expression', hint: 'int' },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'string'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'name:string -> age:int -> < age : int; name : string > Js.t'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: '< age : int; name : string > Js.t'
      },
      { start: [Object], end: [Object], kind: 'core_type', hint: "'a1" },
      { start: [Object], end: [Object], kind: 'core_type', hint: "'a1" },
      { start: [Object], end: [Object], kind: 'core_type', hint: "'a0" },
      { start: [Object], end: [Object], kind: 'core_type', hint: "'a0" },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: "< age : 'a1; name : 'a0 >"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: "< age : 'a1; name : 'a0 > Js.t"
      },
      { start: [Object], end: [Object], kind: 'core_type', hint: "'a1" },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: "age:'a1 -> < age : 'a1; name : 'a0 > Js.t"
      },
      { start: [Object], end: [Object], kind: 'core_type', hint: "'a0" },
      {
        start: [Object],
        end: [Object],
        kind: 'core_type',
        hint: "name:'a0 -> age:'a1 -> < age : 'a1; name : 'a0 > Js.t"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: '< age : int; name : string > Js.t'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: '< age : int; name : string > Js.t'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'binding',
        hint: '< age : int; name : string > Js.t'
      }
    ]
  }
