  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/playground/mel_playground.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/playground/melange-cmijs.js');
  > console.log(ocaml.compileML("let foo bar = ()"));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'function foo(bar) {\n' +
      '  \n' +
      '}\n' +
      '\n' +
      'export {\n' +
      '  foo,\n' +
      '}\n' +
      '/* No side effect */\n',
    warnings: [
      {
        js_warning_error_msg: 'Line 1, 8:\n  Warning: 27 [unused-var-strict] unused variable bar.',
        row: 0,
        column: 8,
        endRow: 0,
        endColumn: 11,
        text: 'unused variable bar.',
        type: 'warning'
      }
    ],
    type_hints: [
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'unit'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: "'a"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: "'a -> unit"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: "'a -> unit"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'binding',
        hint: "'a -> unit"
      }
    ]
  }
