  $ cat > input.js <<EOF
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/jsoo_main.bc.js');
  > require(process.env.DUNE_SOURCEROOT + '/_build/default/bin/melange-cmijs.js');
  > console.log(ocaml.compileML("let foo bar = ()"));
  > EOF

  $ node input.js
  {
    js_code: '// Generated by Melange\n' +
      '\n' +
      '\n' +
      'function foo(bar) {\n' +
      '  \n' +
      '}\n' +
      '\n' +
      'export {\n' +
      '  foo ,\n' +
      '}\n' +
      '/* No side effect */\n',
    type_hints: [
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: 'unit'
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: "'a"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'expression',
        hint: "'a -> unit"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'pattern_type',
        hint: "'a -> unit"
      },
      {
        start: [Object],
        end: [Object],
        kind: 'binding',
        hint: "'a -> unit"
      }
    ]
  }
