;;;;{BSB GENERATED: NO EDIT
(subdir ./libs/number-adder/src
(rule
(targets  NumberAdder.ast)
 (deps (:inputs  NumberAdder.ml) )
(action
 (run melc  -w a  -absname -bs-ast -o %{targets} %{inputs}))
(enabled_if %{bin-available:melc}) )
 (rule
(targets  NumberAdder.d)
 (deps (:inputs  .././src/NumberAdder.ast) )
(action (run meldep -cwd ./src -root /Users/nordfjord/git/nordfjord/melange/jscomp/build_tests/monorepo/./libs/number-adder  %{inputs}))
(enabled_if %{bin-available:melc}) )
 (rule
(targets  NumberAdder.cmj NumberAdder.cmi NumberAdder.cmt NumberAdder.bs.js)
 (mode (promote (until-clean) (only NumberAdder.bs.js)))(deps (:inputs  NumberAdder.ast)  (include NumberAdder.d) ../bsconfig.json)
(action
  (run melc -I .    -w a -bs-package-name @app/number-adder -bs-package-output es6:./src:.bs.js -o NumberAdder.cmj %{inputs}))
(enabled_if %{bin-available:melc}) )
 
(alias (name bsb_world)(deps  NumberAdder.bs.js)
(enabled_if %{bin-available:melc})))


(subdir ./libs/number-adder(data_only_dirs .melange.eobjs))
(subdir ./libs/number-adder/.melange.eobjs)

(subdir ./apps/app/src
(rule
(targets  main.ast)
 (deps (:inputs  main.ml) )
(action
 (run melc  -w a  -absname -bs-ast -o %{targets} %{inputs}))
(enabled_if %{bin-available:melc}) )
 (rule
(targets  main.d)
 (deps (:inputs  .././src/main.ast) )
(action (run meldep -cwd ./src -root /Users/nordfjord/git/nordfjord/melange/jscomp/build_tests/monorepo/./apps/app  %{inputs}))
(enabled_if %{bin-available:melc}) )
 (rule
(targets  main.cmj main.cmi main.cmt main.bs.js)
 (mode (promote (until-clean) (only main.bs.js)))(deps (:inputs  main.ast)  (include main.d) ../bsconfig.json(alias ../../../libs/number-adder/src/bsb_world))
(action
  (run melc -I . -I ../../../libs/number-adder/src   -w a -bs-package-name @app/app -bs-package-output es6:./src:.bs.js -o main.cmj %{inputs}))
(enabled_if %{bin-available:melc}) )
 
(alias (name bsb_world)(deps  main.bs.js)
(enabled_if %{bin-available:melc})))


(subdir ./apps/app(data_only_dirs .melange.eobjs))
(subdir ./apps/app/.melange.eobjs)



(subdir .melange.eobjs)

(data_only_dirs node_modules .melange.eobjs)
(alias (name bsb_world))
;;;;BSB GENERATED: NO EDIT}
