Test that Melange codegen emits module path accesses correctly

  $ dune build @melange-dist

Code accesses Melange__FieldsRequestDescr.Fields.DSL, which is the correct path
for the module.

  $ cat _build/default/dist/main.js
  // Generated by Melange
  'use strict';
  
  const Curry = require("melange.js/curry.js");
  const Melange__FieldsRequestDescr = require("./fieldsRequestDescr.js");
  
  const dr = Curry._1(Melange__FieldsRequestDescr.Fields.Field_dsl.Aggregations.any, 2);
  
  module.exports = {
    dr,
  }
  /* dr Not a pure module */

  $ cd _build/default/dist
  $ node main.js

