
  $ cat > foo.ml <<EOF
  > [@@@mel.config {flags = [| "-unsafe"; "-nopervasives" |] }]
  > let x = 1
  > EOF

  $ melc foo.ml -as-pp foo.ml > foo.pp.ml
  $ melc --as-ppx foo.pp.ml bar.pp.ml

  $ melc ./bar.pp.ml
  // Generated by Melange
  'use strict';
  
  
  var x = 1;
  
  exports.x = x;
  /* No side effect */
