Test `@mel.as` without `@mel.string` / `@mel.int` in external polyvars

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = unit
  > external transition_timing_function :
  >   t ->
  >   [ \`ease
  >   | \`easeIn [@mel.as "ease-in"]
  >   ] ->
  >   unit = "transitionTimingFunction"
  > let () = transition_timing_function () \`easeIn
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  transitionTimingFunction(undefined, "ease-in");
  
  /*  Not a pure module */

  $ cat > x.ml <<EOF
  > type t = unit
  > external transition_timing_function :
  >   t ->
  >   [ \`ease
  >   | \`easeIn [@mel.as 1]
  >   | \`easeOut [@mel.as 2]
  >   ] ->
  >   unit = "transitionTimingFunction"
  > let () = transition_timing_function () \`easeIn
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  transitionTimingFunction(undefined, 1);
  
  /*  Not a pure module */

  $ cat > x.ml <<EOF
  > type t = unit
  > external transition_timing_function :
  >   t ->
  >   [ \`ease
  >   | \`easeIn [@mel.as "ease-in"]
  >   | \`easeOut [@mel.as 1]
  >   ] ->
  >   unit = "transitionTimingFunction"
  > let () = transition_timing_function () \`easeIn
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 6, characters 13-24:
  6 |   | `easeOut [@mel.as 1]
                   ^^^^^^^^^^^
  Error: Expected a string literal
  [2]

  $ cat > x.ml <<EOF
  > type t = unit
  > external transition_timing_function :
  >   t ->
  >   [ \`ease
  >   | \`easeIn [@mel.as 1] [@mel.as "ease-in"]
  >   | \`easeOut
  >   ] ->
  >   unit = "transitionTimingFunction"
  > let () = transition_timing_function () \`easeIn
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 5, characters 4-43:
  5 |   | `easeIn [@mel.as 1] [@mel.as "ease-in"]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Error: Duplicate `@mel.as'
  [2]

