Demonstrate redefining the `true` / `false` constructors

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = A | true | false
  > let z : t = A
  > let x : t = true
  > let y : t = false
  > let t : bool = false
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const z = /* A */ 0;
  
  const x = /* true */ 1;
  
  const y = /* false */ 2;
  
  const t = false;
  
  module.exports = {
    z,
    x,
    y,
    t,
  }
  /* No side effect */
