Demonstrate redefining the `true` / `false` constructors

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = A | true | false
  > let z : t = A
  > let x : t = true
  > let y : t = false
  > let t : bool = false
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const z = /* A */0;
  
  const x = true;
  
  const y = true;
  
  const t = false;
  
  exports.z = z;
  exports.x = x;
  exports.y = y;
  exports.t = t;
  /* No side effect */
