Demonstrate how default exports are handlded

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let default = 1
  > EOF

With commonjs

  $ melc -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  'use strict';
  
  
  var $$default = 1;
  
  exports.$$default = $$default;
  exports.default = $$default;
  exports.__esModule = true;
  /* No side effect */

With es6

  $ melc -bs-module-type es6 -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  
  
  var $$default = 1;
  
  export {
    $$default ,
    $$default as default,
  }
  /* No side effect */

