Demonstrate how default exports are handlded

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let default = 1
  > EOF

With commonjs

  $ melc -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  'use strict';
  
  
  var $$default = 1;
  
  exports.$$default = $$default;
  /* No side effect */

With es6

  $ melc -bs-module-type es6 -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  
  
  var $$default = 1;
  
  export {
    $$default ,
  }
  /* No side effect */

With default export value

  $ cat > x.ml <<EOF
  > let __es6__default_export = 1
  > EOF

Commonjs

  $ melc -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  'use strict';
  
  
  var __es6__default_export = 1;
  
  exports.default = __es6__default_export;
  exports.__esModule = true;
  /* No side effect */

Es6

  $ melc -bs-module-type es6 -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  
  
  var __es6__default_export = 1;
  
  export {
    __es6__default_export as default,
  }
  /* No side effect */
