
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > [%%raw {||}]
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  
  'use strict';
  
  
  /* No side effect */

  $ cat > x.ml <<EOF
  > let () = [%raw {||}]
  > EOF
  $ melc -ppx melppx x.ml | tee x.js
  File "x.ml", line 1, characters 17-17:
  Warning 103 [melange-ffi-warning]: FFI warning: Unexpected end of input
  // Generated by Melange
  'use strict';
  
  
  ();
  /*  Not a pure module */

  $ node ./x.js 2>&1 | grep -vi node
  $TESTCASE_ROOT/x.js:5
  ();
   ^
  
  SyntaxError: Unexpected token ')'
  

  $ cat > x.ml <<EOF
  > let x = [%raw {||}]
  > EOF
  $ melc -ppx melppx x.ml | tee x.js
  File "x.ml", line 1, characters 16-16:
  Warning 103 [melange-ffi-warning]: FFI warning: Unexpected end of input
  // Generated by Melange
  'use strict';
  
  
  const x = ;
  
  module.exports = {
    x,
  }
  /* x Not a pure module */

  $ node ./x.js 2>&1 | grep -vi node
  $TESTCASE_ROOT/x.js:5
  const x = ;
            ^
  
  SyntaxError: Unexpected token ';'
  
