
  $ . ./setup.sh
  $ cat > dune-project <<EOF
  > (lang dune 3.13)
  > (using melange 0.1)
  > EOF
  $ cat > dune <<EOF
  > (melange.emit
  >  (target out)
  >  (preprocess (pps melange.ppx)))
  > EOF
  $ cat > x.ml <<EOF
  > let () =
  >   try [%mel.raw "(function () { throw undefined })()"]
  >   with exn -> raise exn
  > EOF

  $ dune build @melange
  $ cat _build/default/out/x.js
  // Generated by Melange
  'use strict';
  
  const Caml_js_exceptions = require("melange.js/caml_js_exceptions.js");
  
  try {
    (((function () { throw undefined })()
      ));
  }
  catch (exn){
    throw new Caml_js_exceptions.MelangeError(exn.MEL_EXN_ID, exn);
  }
  /*  Not a pure module */

  $ node _build/default/out/x.js 2>&1 | grep -v Node | grep -vE '\s+at'
  $TESTCASE_ROOT/_build/default/out/x.js:11
    throw new Caml_js_exceptions.MelangeError(exn.MEL_EXN_ID, exn);
                                                  ^
  
  TypeError: Cannot read properties of undefined (reading 'MEL_EXN_ID')
  


