
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let () =
  >   try [%mel.raw "(function () { throw undefined })()"]
  >   with exn -> raise exn
  > EOF

  $ melc -ppx melppx x.ml | tee x.js
  // Generated by Melange
  'use strict';
  
  const Caml_js_exceptions = require("melange.js/caml_js_exceptions.js");
  
  try {
    (((function () { throw undefined })()
      ));
  }
  catch (exn){
    throw new Caml_js_exceptions.MelangeError(exn.MEL_EXN_ID, exn);
  }
  /*  Not a pure module */

  $ node x.js 2>&1 | grep -v Node | grep -vE '\s+at'
  $TESTCASE_ROOT/x.js:11
    throw new Caml_js_exceptions.MelangeError(exn.MEL_EXN_ID, exn);
                                                  ^
  
  TypeError: Cannot read properties of undefined (reading 'MEL_EXN_ID')
  

