
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > exception Error of string
  > module Error = struct 
  >   let x = 1
  > end
  > EOF

  $ melc -ppx melppx ./x.ml > x.js
  $ sed '/^$/d' x.js
  // Generated by Melange
  'use strict';
  const Caml_exceptions = require("melange.js/caml_exceptions.js");
  const $$Error$1 = /* @__PURE__ */ Caml_exceptions.create("X.Error");
  const $$Error = {
    x: 1
  };
  module.exports = {
    Error$1: $$Error$1,
    $$Error,
  }
  /* No side effect */

The preferred local name is independent of declaration order, for both
module/exception and value/class collisions and in both module systems.

  $ cat > priorities.ml <<EOF
  > module Forward = struct
  >   let x = 2
  > end
  > exception Forward of string
  > class item = object end
  > let item = 1
  > let direct = 2
  > class direct = object end
  > module Alias_base = struct
  >   let x = 3
  > end
  > module Aliased = struct
  >   module Item = Alias_base
  >   exception Item
  > end
  > module Present = struct
  >   module Item = struct
  >     let x = 4
  >   end
  >   exception Item of string
  > end
  > module Source = struct
  >   module Clash = struct
  >     let x = 5
  >   end
  >   exception Clash of string
  > end
  > module Narrow : sig
  >   exception Clash of string
  > end = Source
  > module Reordered : sig
  >   exception Clash of string
  >   module Clash : sig
  >     val x : int
  >   end
  > end = Source
  > module Composed : sig
  >   exception Clash of string
  > end = ((Source : sig
  >   exception Clash of string
  >   module Clash : sig end
  > end) : sig
  >   exception Clash of string
  > end)
  > module Class_source = struct
  >   class item = object
  >     method value = 6
  >   end
  >   let item = 7
  > end
  > module Class_only : sig
  >   class item : object
  >     method value : int
  >   end
  > end = Class_source
  > module rec Recursive : sig
  >   val delete : unit -> int
  >   class delete : object
  >     method value : int
  >   end
  > end = struct
  >   class delete = object
  >     method value = 8
  >   end
  >   let delete () = 9
  > end
  > module Structured : sig
  >   exception Clash of int
  >   val value : int
  >   module Clash : sig val value : int end
  >   val captured : int
  > end = struct
  >   open struct let value = 10 end
  >   let captured = value
  >   let value = 11
  >   module Clash = struct let value = 12 end
  >   include struct exception Clash of int end
  > end
  > module Mixed = struct
  >   type t = ..
  >   type t += Clash of int
  >   module type S = sig end
  >   external item : int -> int = "%identity"
  >   class item = object method value = 11 end
  >   module Clash = struct let value = 12 end
  >   let tail = 13
  > end
  > EOF
  $ melc -ppx melppx -bs-package-output . priorities.ml -o priorities.js
  $ melc -bs-module-type es6 priorities.cmj -o priorities.mjs
  $ node <<'EOF'
  > const assert = require("node:assert/strict");
  > const fs = require("node:fs");
  > for (const file of ["priorities.js", "priorities.mjs"]) {
  >   const source = fs.readFileSync(file, "utf8");
  >   assert.match(source, /const Forward = \{/);
  >   assert.match(source, /const Forward\$1 = .*Caml_exceptions\.create/);
  >   assert.match(source, /const item\$1 = /);
  >   assert.match(source, /const item = 1;/);
  >   assert.match(source, /const direct = 2;/);
  >   assert.match(source, /const direct\$1 = /);
  > }
  > EOF

An identically named module alias must not capture an exception path during
cross-unit path normalization. Direct structure coercion must account for hidden
open bindings, shadowing, and included exceptions. Primitives and module types
must not reserve runtime fields.

  $ cat > consumer.ml <<EOF
  > let module_value = Priorities.Aliased.Item.x
  > let exception_value = Priorities.Aliased.Item
  > let present_module = Priorities.Present.Item.x
  > let present =
  >   try raise (Priorities.Present.Item "present") with
  >   | Priorities.Present.Item value -> value
  > let narrow =
  >   try raise (Priorities.Narrow.Clash "narrow") with
  >   | Priorities.Narrow.Clash value -> value
  > let reordered_module = Priorities.Reordered.Clash.x
  > let reordered =
  >   try raise (Priorities.Reordered.Clash "reordered") with
  >   | Priorities.Reordered.Clash value -> value
  > let composed =
  >   try raise (Priorities.Composed.Clash "composed") with
  >   | Priorities.Composed.Clash value -> value
  > let class_value = (new Priorities.Class_only.item)#value
  > let recursive_value = Priorities.Recursive.delete ()
  > let recursive_class_value = (new Priorities.Recursive.delete)#value
  > let structured =
  >   let caught =
  >     try raise (Priorities.Structured.Clash 13) with
  >     | Priorities.Structured.Clash value -> value
  >   in
  >   (Priorities.Structured.captured, Priorities.Structured.value,
  >    Priorities.Structured.Clash.value, caught)
  > let mixed =
  >   let matched = match Priorities.Mixed.Clash 10 with
  >     | Priorities.Mixed.Clash value -> value
  >     | _ -> assert false
  >   in
  >   (matched, (new Priorities.Mixed.item)#value,
  >    Priorities.Mixed.Clash.value, Priorities.Mixed.item Priorities.Mixed.tail)
  > EOF
  $ melc -ppx melppx -I . -bs-package-output . consumer.ml -o consumer.js
  $ melc -bs-module-type es6 -I . consumer.cmj -o consumer.mjs
  $ node --input-type=module <<'EOF'
  > import assert from "node:assert/strict";
  > for (const suffix of ["js", "mjs"]) {
  >   const priorities = await import(`./priorities.${suffix}`).then(m => m.default ?? m);
  >   const consumer = await import(`./consumer.${suffix}`).then(m => m.default ?? m);
  >   assert.equal(consumer.module_value, 3);
  >   assert.equal(consumer.exception_value.MEL_EXN_ID, priorities.Aliased.Item);
  >   assert.equal(consumer.present_module, 4);
  >   assert.equal(consumer.present, "present");
  >   assert.deepEqual(Object.keys(priorities.Present), ["Item", "Item$1"]);
  >   assert.equal(consumer.narrow, "narrow");
  >   assert.deepEqual(Object.keys(priorities.Narrow), ["Clash"]);
  >   assert.equal(consumer.reordered_module, 5);
  >   assert.equal(consumer.reordered, "reordered");
  >   assert.equal(consumer.composed, "composed");
  >   assert.equal(consumer.class_value, 6);
  >   assert.equal(consumer.recursive_value, 9);
  >   assert.equal(consumer.recursive_class_value, 8);
  >   assert.equal(priorities.item, 1);
  >   assert.ok(Object.hasOwn(priorities, "item$1"));
  >   assert.equal(priorities.direct, 2);
  >   assert.ok(Object.hasOwn(priorities, "direct$1"));
  >   assert.deepEqual(consumer.structured, [10, 11, 12, 13]);
  >   assert.deepEqual(consumer.mixed, [10, 11, 12, 13]);
  >   assert.deepEqual(Object.keys(priorities.Mixed), ["Clash$1", "item", "Clash", "tail"]);
  > }
  > EOF

A restrictive interface reads a collision-resolved source field and publishes
the target signature's unambiguous name.

  $ cat > restricted.mli <<EOF
  > exception Clash of string
  > val keep : int
  > EOF
  $ cat > restricted.ml <<EOF
  > module Clash = struct end
  > exception Clash of string
  > let keep = 8
  > EOF
  $ cat > restricted_consumer.ml <<EOF
  > let result =
  >   try raise (Restricted.Clash "restricted") with
  >   | Restricted.Clash value -> value
  > EOF
  $ melc -ppx melppx --intf restricted.mli -o restricted.cmi
  $ melc -ppx melppx -I . restricted.ml -o restricted.js
  $ melc -ppx melppx -I . restricted_consumer.ml -o restricted_consumer.js
  $ node <<'EOF'
  > const assert = require("node:assert/strict");
  > const restricted = require("./restricted.js");
  > const consumer = require("./restricted_consumer.js");
  > assert.deepEqual(Object.keys(restricted), ["Clash", "keep"]);
  > assert.equal(consumer.result, "restricted");
  > EOF
