An exception should not resolve through a module alias with the same name.
This currently crashes during exception lookup.

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > module Base = struct end
  > module M = struct
  >   module E = Base
  >   exception E
  > end
  > let e = M.E
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  const Caml_exceptions = require("melange.js/caml_exceptions.js");
  const Caml_js_exceptions = require("melange.js/caml_js_exceptions.js");
  
  const Base = {};
  
  const E = /* @__PURE__ */ Caml_exceptions.create("X.M.E");
  
  const M = {
    E
  };
  
  const e = new Caml_js_exceptions.MelangeError(E, {
      MEL_EXN_ID: E
    });
  
  module.exports = {
    Base,
    M,
    e,
  }
  /* No side effect */
