Export otherwise invalid OCaml identifiers to JavaScript

  $ . ./setup.sh
  $ cat > dune-project <<EOF
  > (lang dune 3.8)
  > (using melange 0.1)
  > EOF
  $ cat > dune <<EOF
  > (melange.emit
  >  (compile_flags -w -32)
  >  (emit_stdlib false)
  >  (preprocess (pps melange.ppx))
  >  (target js-out))
  > EOF

  $ cat > x.ml <<EOF
  > let [@mel.as POST] post= 1
  > let [@mel.as "GET"] get = 2
  > let [@mel.as "put"] other = 2
  > EOF

  $ cat > x.mli <<EOF
  > val [@mel.as "GET"] get : int
  > EOF

  $ dune build @melange

  $ cat _build/default/js-out/x.js
  // Generated by Melange
  'use strict';
  
  
  var get = 2;
  
  var GET = 2;
  
  exports.get = get;
  exports.GET = GET;
  /* No side effect */
