Export otherwise invalid OCaml identifiers to JavaScript

  $ . ./setup.sh
  $ cat > dune-project <<EOF
  > (lang dune 3.8)
  > (using melange 0.1)
  > EOF
  $ cat > dune <<EOF
  > (melange.emit
  >  (compile_flags -w -32)
  >  (emit_stdlib false)
  >  (preprocess (pps melange.ppx))
  >  (target js-out))
  > EOF

  $ cat > x.ml <<EOF
  > let [@mel.for_js POST] post= 1
  > let [@mel.for_js "GET"] get = 2
  > let [@mel.for_js "put"] other = 2
  > let [@mel.for_js "class"] other = 2 (* class is reserved in JS *)
  > EOF

  $ cat > x.mli <<EOF
  > val [@mel.for_js "GET"] get : int
  > val [@mel.for_js "class"] other : int
  > EOF

  $ dune build @melange

  $ cat _build/default/js-out/x.js
  // Generated by Melange
  'use strict';
  
  
  var GET = 2;
  
  var $$class = 2;
  
  exports.GET = GET;
  exports.$$class = $$class;
  /* No side effect */

  $ cat > z.ml <<EOF
  > let post = 1
  > let [@mel.for_js "POST"] js_post = post
  > EOF

  $ cat > a.ml <<EOF
  > let post = Z.post
  > EOF

  $ dune build @melange

  $ cat _build/default/js-out/z.js
  // Generated by Melange
  'use strict';
  
  
  var post = 1;
  
  var POST = 1;
  
  exports.post = post;
  exports.POST = POST;
  /* No side effect */
