  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > external f : int = ""
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 1, characters 0-21:
  1 | external f : int = ""
      ^^^^^^^^^^^^^^^^^^^^^
  Alert fragile: f : the external name is inferred from val name is unsafe from refactoring when changing value name
  // Generated by Melange
  /* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */
