Showcase some issues with silencing of melange ppx alerts

  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > let (foo [@alert deprecated "there"]) = fun () -> 1
  > let _ = foo ()
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 2, characters 8-11:
  2 | let _ = foo ()
              ^^^
  Alert deprecated: foo
  there
  // Generated by Melange
  'use strict';
  
  
  function foo(param) {
    return 1;
  }
  
  exports.foo = foo;
  /* No side effect */

Silencing normal alerts in-file works

  $ cat > x.ml <<EOF
  > [@@@alert "-deprecated"]
  > let (foo [@alert deprecated "there"]) = fun () -> 1
  > let _ = foo ()
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  function foo(param) {
    return 1;
  }
  
  exports.foo = foo;
  /* No side effect */

Show alert when using @bs

  $ cat > x.ml <<EOF
  > let t = (fun [@bs] a -> a)
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 1, characters 15-17:
  1 | let t = (fun [@bs] a -> a)
                     ^^
  Alert deprecated: The `[@bs]' uncurry attribute is deprecated and will be removed in the next release.
  Use `[@u]' instead.
  // Generated by Melange
  'use strict';
  
  
  function t(a) {
    return a;
  }
  
  exports.t = t;
  /* No side effect */

  $ cat > x.ml <<EOF
  > [@@@alert "-deprecated"]
  > let t = (fun [@bs] a -> a)
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 2, characters 15-17:
  2 | let t = (fun [@bs] a -> a)
                     ^^
  Alert deprecated: The `[@bs]' uncurry attribute is deprecated and will be removed in the next release.
  Use `[@u]' instead.
  // Generated by Melange
  'use strict';
  
  
  function t(a) {
    return a;
  }
  
  exports.t = t;
  /* No side effect */
