Demonstrate different file extensions

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let () = Js.log "hello"
  > EOF

Specify the output filename with `-o`

  $ melc -impl x.ml -o x.js
  $ cat x.js
  // Generated by Melange
  'use strict';
  
  
  console.log("hello");
  
  /*  Not a pure module */

Try other extensions

  $ melc -impl x.ml -o x.bs.js
  $ cat x.bs.js
  // Generated by Melange
  'use strict';
  
  
  console.log("hello");
  
  /*  Not a pure module */

  $ melc -impl x.ml -o x.ml.js
  $ cat x.ml.js
  // Generated by Melange
  'use strict';
  
  
  console.log("hello");
  
  /*  Not a pure module */

  $ melc -impl x.ml -o x.melange.js
  $ cat x.melange.js
  // Generated by Melange
  'use strict';
  
  
  console.log("hello");
  
  /*  Not a pure module */

  $ rm *
  $ cat > x.ml <<EOF
  > let () = Js.log "hello"
  > EOF
  $ melc -impl x.ml -o x.foo.
  $ ls
  x.foo.cmi
  x.foo.cmj
  x.foo.cmt
  x.foo.js
  x.ml

  $ rm *
  $ cat > x.ml <<EOF
  > let () = Js.log "hello"
  > EOF
  $ melc -impl x.ml -o x
  $ ls
  x.cmi
  x.cmj
  x.cmt
  x.js
  x.ml

  $ rm *
  $ cat > x.ml <<EOF
  > let () = Js.log "hello"
  > EOF
  $ melc -impl x.ml -o x....
  $ ls
  x....cmi
  x....cmj
  x....cmt
  x....js
  x.ml
