
  $ . ./setup.sh
  $ cat > main.ml <<EOF
  > let f x =
  >   let rec aux x k =
  >     match x with
  >     | 0 -> k 0
  >     | x -> aux (x - 1) (fun x -> x)
  >   in
  >   aux x (fun x -> x)
  > let _: int = f 3
  > EOF

  $ melc main.ml | tee main.js
  // Generated by Melange
  'use strict';
  
  const Curry = require("melange.js/curry.js");
  
  function f(x) {
    let _x = x;
    let _k = function (x) {
      return x;
    };
    while (true) {
      const k = _k;
      const x$1 = _x;
      if (x$1 === 0) {
        return Curry._1(k, 0);
      }
      _k = (function (x) {
        return x;
      });
      _x = x$1 - 1 | 0;
      continue;
    };
  }
  
  f(3);
  
  module.exports = {
    f,
  }
  /*  Not a pure module */

