

  $ . ./setup.sh
  $ cat > dune-project <<EOF
  > (lang dune 3.8)
  > (using melange 0.1)
  > EOF
  $ cat > dune <<EOF
  > (melange.emit
  >  (target output)
  >  (emit_stdlib false))
  > EOF
  $ cat > x.ml <<EOF
  > let v1: int = 2_147_483_647 (* max int *)
  > let v2: int = 2_147_483_648 (* overflow *)
  > let v3: int = 2_147_483_649 (* overflow *)
  > let v4: int = -2_147_483_647
  > let v5: int = -2_147_483_648 (* min int *)
  > let v6: int = -2_147_483_649 (* underflow *)
  > (* hex *)
  > let v7: int = 0xFFFF_FFFF (* -1 *)
  > let v8: int = -0xFFFF_FFFF (* 1 *)
  > let v9:int = 0x1_0000_0000 (* overflow *)
  > let v10:int = -0x1_0000_0000 (* underflow *)
  > EOF

  $ dune build @melange
  File "x.ml", line 2, characters 14-27:
  2 | let v2: int = 2_147_483_648 (* overflow *)
                    ^^^^^^^^^^^^^
  Warning 107 [melange-literal-int-overflow]: Integer literal exceeds the range of representable integers of type int
  
  File "x.ml", line 3, characters 14-27:
  3 | let v3: int = 2_147_483_649 (* overflow *)
                    ^^^^^^^^^^^^^
  Warning 107 [melange-literal-int-overflow]: Integer literal exceeds the range of representable integers of type int
  
  File "x.ml", line 6, characters 14-28:
  6 | let v6: int = -2_147_483_649 (* underflow *)
                    ^^^^^^^^^^^^^^
  Warning 107 [melange-literal-int-overflow]: Integer literal exceeds the range of representable integers of type int
  
  File "x.ml", line 10, characters 13-26:
  10 | let v9:int = 0x1_0000_0000 (* overflow *)
                    ^^^^^^^^^^^^^
  Warning 107 [melange-literal-int-overflow]: Integer literal exceeds the range of representable integers of type int
  
  File "x.ml", line 11, characters 14-28:
  11 | let v10:int = -0x1_0000_0000 (* underflow *)
                     ^^^^^^^^^^^^^^
  Warning 107 [melange-literal-int-overflow]: Integer literal exceeds the range of representable integers of type int
  $ cat ./_build/default/output/x.js
  // Generated by Melange
  'use strict';
  
  
  var v1 = 2147483647;
  
  var v2 = -2147483648;
  
  var v3 = -2147483647;
  
  var v4 = -2147483647;
  
  var v5 = -2147483648;
  
  var v6 = 2147483647;
  
  var v7 = -1;
  
  var v8 = 1;
  
  var v9 = 0;
  
  var v10 = 0;
  
  exports.v1 = v1;
  exports.v2 = v2;
  exports.v3 = v3;
  exports.v4 = v4;
  exports.v5 = v5;
  exports.v6 = v6;
  exports.v7 = v7;
  exports.v8 = v8;
  exports.v9 = v9;
  exports.v10 = v10;
  /* No side effect */
