
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let sum_and_product ints =
  >   let init = ~sum:0, ~product:1 in
  >   List.fold_left (fun (~sum, ~product) elem ->
  >     let sum = elem + sum in
  >     let product = elem * product in
  >     ~sum, ~product) init ints
  > EOF

  $ melc  ./x.ml
  // Generated by Melange
  'use strict';
  
  const Stdlib__List = require("melange/list.js");
  
  function sum_and_product(ints) {
    return Stdlib__List.fold_left((function (param, elem) {
      const sum = elem + param[0] | 0;
      const product = Math.imul(elem, param[1]);
      return [
        sum,
        product
      ];
    }), [
      0,
      1
    ], ints);
  }
  
  module.exports = {
    sum_and_product,
  }
  /* No side effect */
  $ melc -ppx melppx ./x.ml 2>&1 | grep -i error
  Error: migration error: labelled tuples are not supported before OCaml 5.4
  melc: internal error, uncaught exception:
        Melangelib.Cmd_ast_exception.Error(_)
