A test case for some exn in lam_convert

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let t = (Stdlib.abs_float  [@ocaml.alert "-deprecated"]);
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  
  function t(prim) {
    return Math.abs(prim);
  }
  
  exports.t = t;
  /* No side effect */
