Test `@mel.as` in variant constructors

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = Null [@mel.as null] | Undefined [@mel.as undefined] | Other
  > let x = Null
  > let y = Undefined
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = /* Null */ null;
  
  let y;
  
  module.exports = {
    x,
    y,
  }
  /* No side effect */

  $ cat > x.ml <<EOF
  > type t =
  >   | Should_be_null [@mel.as null]
  >   | Should_be_undefined [@mel.as undefined]
  >   | Should_be_string [@mel.as "the_string"]
  > let x = Should_be_null
  > let y = Should_be_undefined
  > let z = Should_be_string
  > let f = function
  >   | Should_be_null -> "null"
  >   | Should_be_undefined -> "undefined"
  >   | Should_be_string -> "string"
  > let () =
  >   Js.log (f Should_be_null);
  >   Js.log (f Should_be_undefined);
  >   Js.log (f Should_be_string)
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  function f(param) {
    switch (param) {
      case /* Should_be_null */ null :
        return "null";
      case /* Should_be_undefined */ undefined :
        return "undefined";
      case /* Should_be_string */ "the_string" :
        return "string";
    }
  }
  
  console.log("null");
  
  console.log("undefined");
  
  console.log("string");
  
  const x = /* Should_be_null */ null;
  
  let y;
  
  const z = /* Should_be_string */ "the_string";
  
  module.exports = {
    x,
    y,
    z,
    f,
  }
  /*  Not a pure module */

  $ cat > x.ml <<EOF
  > type t =
  >   | Null_no_payload [@mel.as null]
  >   | Undefined_no_payload [@mel.as undefined]
  >   | String_no_payload [@mel.as "the_string"]
  >   | Null_has_payload of string [@mel.as null]
  >   | Undefined_has_payload of int [@mel.as undefined]
  > let z = Null_has_payload "p1"
  > let t = Undefined_has_payload 42
  > let y = Undefined_no_payload
  > let f = function
  >   | Null_no_payload -> "null"
  >   | Undefined_no_payload -> "undefined"
  >   | String_no_payload -> "string"
  >   | Null_has_payload s -> s
  >   | Undefined_has_payload n -> string_of_int n
  > let () =
  >   Js.log (f (Undefined_has_payload 83));
  >   Js.log (f (Null_has_payload "null payload"));
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  function f(s) {
    if (!(s === null || typeof s !== "object")) {
      if (s.TAG === /* Null_has_payload */ null) {
        return s._0;
      } else {
        return String(s._0);
      }
    }
    switch (s) {
      case /* Null_no_payload */ null :
        return "null";
      case /* Undefined_no_payload */ undefined :
        return "undefined";
      case /* String_no_payload */ "the_string" :
        return "string";
    }
  }
  
  console.log(String(83));
  
  console.log("null payload");
  
  const z = {
    TAG: /* Null_has_payload */ null,
    _0: "p1"
  };
  
  const t = {
    TAG: /* Undefined_has_payload */ undefined,
    _0: 42
  };
  
  let y;
  
  module.exports = {
    z,
    t,
    y,
    f,
  }
  /*  Not a pure module */

