Test `@mel.as` in variant constructors

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = Not_A [@mel.as "A"] | Not_B [@mel.as "B"] | Not_C
  > let x = Not_A
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = "A";
  
  exports.x = x;
  /* No side effect */
