Test `@mel.invoke + labeled / optional arguments

  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > type 'a t = 'a array
  > external push : ?value:'a -> 'a t -> int = "push" [@@mel.invoke]
  > let x =
  >   let arr = [| 0; 1; 2 |] in
  >   push arr ~value:3
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const arr = [
    0,
    1,
    2
  ];
  
  const x = arr.push(3);
  
  exports.x = x;
  /* x Not a pure module */

