Test `@mel.send` + labeled / optional arguments

  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > type 'a t = 'a array
  > external push : ?value:'a -> 'a t -> int = "push" [@@mel.send]
  > let x =
  >   let arr = [| 0; 1; 2 |] in
  >   push arr
  > EOF

This specific behavior emits an alert

  $ melc -ppx melppx x.ml
  File "x.ml", line 2, characters 0-62:
  2 | external push : ?value:'a -> 'a t -> int = "push" [@@mel.send]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Alert melsend: [@mel.send] "self" param changed in Melange 5.x. It is now the first non-labeled parameter in the `external' declaration. Check this FFI definition accordingly.
  // Generated by Melange
  'use strict';
  
  
  const arr = [
    0,
    1,
    2
  ];
  
  const x = arr.push(undefined);
  
  exports.x = x;
  /* x Not a pure module */

We can suppress the alert to get the new, improved behavior

  $ melc -ppx "melppx -alert -melsend" x.ml
  // Generated by Melange
  'use strict';
  
  
  const arr = [
    0,
    1,
    2
  ];
  
  const x = arr.push(undefined);
  
  exports.x = x;
  /* x Not a pure module */
