The last payload-bearing `[@@mel.module]` attribute wins, including its optional
JavaScript binding name.

  $ . ./setup.sh

Reversing the attributes changes which module supplies the value.

  $ cat > x.ml <<EOF
  > external first_then_second : int = "value"
  > [@@mel.module "first"] [@@mel.module "second"]
  > external second_then_first : int = "value"
  > [@@mel.module "second"] [@@mel.module "first"]
  > let first_then_second = first_then_second
  > let second_then_first = second_then_first
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  const First = require("first");
  const Second = require("second");
  
  const first_then_second = Second.value;
  
  const second_then_first = First.value;
  
  module.exports = {
    first_then_second,
    second_then_first,
  }
  /* first_then_second Not a pure module */

The last tuple payload replaces both the module path and the binding name.

  $ cat > x.ml <<EOF
  > external value : int = "value"
  > [@@mel.module ("first", "FirstHint")]
  > [@@mel.module ("second", "SecondHint")]
  > let value = value
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  const SecondHint = require("second");
  
  const value = SecondHint.value;
  
  module.exports = {
    value,
  }
  /* value Not a pure module */

Switching between string and tuple payloads clears or sets the binding name.

  $ cat > x.ml <<EOF
  > external clear_hint : int = "value"
  > [@@mel.module ("ignored-clear", "Ignored")]
  > [@@mel.module "clear"]
  > external set_hint : int = "value"
  > [@@mel.module "ignored-set"]
  > [@@mel.module ("set", "Chosen")]
  > let clear_hint = clear_hint
  > let set_hint = set_hint
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  const Clear = require("clear");
  const Chosen = require("set");
  
  const clear_hint = Clear.value;
  
  const set_hint = Chosen.value;
  
  module.exports = {
    clear_hint,
    set_hint,
  }
  /* clear_hint Not a pure module */
