Test that `@mel.as` can generate empty strings

  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > type t = A [@mel.as ""]
  > external foo: [ \`Foo [@mel.as ""] ] -> unit = "someFn"
  > let t = A
  > let () = foo \`Foo
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  someFn("");
  
  const t = /* A */ "";
  
  module.exports = {
    t,
  }
  /*  Not a pure module */
