
  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > external foo : ([ \`bar of string ][@mel.int]) -> unit = "someFnCall"
  > let () = foo (\`bar "hello")
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  someFnCall(0, "hello");
  /*  Not a pure module */

  $ cat > x.ml <<EOF
  > external foo :
  >   ([ \`foo of string
  >    | \`bar of string [@mel.as 42]
  >    | \`baz of string ]
  >   [@mel.int]) ->
  >   unit = "someFnCall"
  > let () =
  >   foo (\`foo "hello");
  >   foo (\`bar "world");
  >   foo (\`baz "!")
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  someFnCall(0, "hello");
  
  someFnCall(42, "world");
  
  someFnCall(43, "!");
  /*  Not a pure module */
