
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t
  > external f: int -> (_ [@mel.as "x"] [@mel.this]) -> unit = "set"
  > [@@mel.send]
  > let () = f 3
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  "x".set(3);
  /*  Not a pure module */

  $ cat > x.ml <<EOF
  > type t
  > external f: int -> (_ [@mel.as "x"] [@mel.this]) -> int -> unit = "set"
  > [@@mel.send]
  > let () = f 3 4
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  "x".set(3, 4);
  /*  Not a pure module */
