Test the attribute @mel.as in external with @mel.set

  $ . ./setup.sh

  $ cat > x.ml <<'EOF'
  > type document
  > 
  > external document : document = "document"
  > 
  > external transition :
  >   document ->
  >   [ `ease
  >   | `easeIn [@mel.as "ease-in"]
  >   | `easeOut [@mel.as "ease-out"]
  >   | `easeInOut [@mel.as "ease-in-out"]
  >   | `linear ] ->
  >   unit = "transitionTimingFunction"
  > [@@mel.set]
  > 
  > let () = transition document `easeIn
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  document.transitionTimingFunction = "ease-in";
  /*  Not a pure module */

  $ cat > x.ml <<'EOF'
  > type document
  > 
  > external document : document = "document"
  > 
  > external transition :
  >   document ->
  >   ([ `ease
  >   | `easeIn [@mel.as "ease-in"]
  >   | `easeOut [@mel.as "ease-out"]
  >   | `easeInOut [@mel.as "ease-in-out"]
  >   | `linear ] [@mel.string]) ->
  >   unit = "transitionTimingFunction"
  > [@@mel.set]
  > 
  > let () = transition document `easeIn
  > EOF

Using @mel.string fixes it

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  document.transitionTimingFunction = "ease-in";
  /*  Not a pure module */
