Test `@mel.as` in variant constructors

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = ThisIsTrue [@mel.as true] | ThisIsFalse [@mel.as false]
  > let x = ThisIsTrue
  > let y = ThisIsFalse
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = /* ThisIsTrue */ true;
  
  const y = /* ThisIsFalse */ false;
  
  module.exports = {
    x,
    y,
  }
  /* No side effect */

  $ cat > x.ml <<EOF
  > module Opp1 = struct
  >   type t = true [@mel.as false] | false [@mel.as true]
  > end
  > module Opp2 = struct
  >   type t = false [@mel.as true] | true [@mel.as false]
  > end
  > let t = let open Opp1 in false
  > let f = let open Opp1 in true
  > let t2 = let open Opp2 in false
  > let f2 = let open Opp2 in true
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const Opp1 = {};
  
  const Opp2 = {};
  
  const t = /* false */ true;
  
  const f = /* true */ false;
  
  const t2 = /* false */ true;
  
  const f2 = /* true */ false;
  
  module.exports = {
    Opp1,
    Opp2,
    t,
    f,
    t2,
    f2,
  }
  /* No side effect */
