Test `@mel.as` in `@mel.obj`

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > external func :
  >   foo:(string [@mel.as "bar"]) ->
  >   ?polyParam1:([ \`Str of string | \`Int of int ][@mel.as "poly-param1"]) ->
  >   ?polyParam2:([ \`Str of string | \`Int of int ][@mel.unwrap][@mel.as "poly-param2"]) ->
  >   unit -> _ = ""
  > [@@mel.obj]
  > let x = func ~foo:"x" ~polyParam1:(\`Str "hello") ~polyParam2:(\`Int 5) ()
  > (* wildcard [@mel.as] constants still work *)
  > external ff : hi:int -> lo:(_ [@mel.as 3]) -> _ Js.t = "" [@@mel.obj]
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 2, characters 16-22:
  2 |   foo:(string [@mel.as "bar"]) ->
                      ^^^^^^
  Alert unused: Unused attribute [@mel.as]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  
  File "x.ml", line 3, characters 49-55:
  3 |   ?polyParam1:([ `Str of string | `Int of int ][@mel.as "poly-param1"]) ->
                                                       ^^^^^^
  Alert unused: Unused attribute [@mel.as]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  
  File "x.ml", line 4, characters 62-68:
  4 |   ?polyParam2:([ `Str of string | `Int of int ][@mel.unwrap][@mel.as "poly-param2"]) ->
                                                                    ^^^^^^
  Alert unused: Unused attribute [@mel.as]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  
  File "x.ml", line 2, characters 16-22:
  2 |   foo:(string [@mel.as "bar"]) ->
                      ^^^^^^
  Alert unused: Unused attribute [@mel.as]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  
  File "x.ml", line 3, characters 49-55:
  3 |   ?polyParam1:([ `Str of string | `Int of int ][@mel.as "poly-param1"]) ->
                                                       ^^^^^^
  Alert unused: Unused attribute [@mel.as]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  
  File "x.ml", line 4, characters 62-68:
  4 |   ?polyParam2:([ `Str of string | `Int of int ][@mel.unwrap][@mel.as "poly-param2"]) ->
                                                                    ^^^^^^
  Alert unused: Unused attribute [@mel.as]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  // Generated by Melange
  'use strict';
  
  
  var x = {
    foo: "x",
    polyParam1: {
      NAME: "Str",
      VAL: "hello"
    },
    polyParam2: 5
  };
  
  exports.x = x;
  /* No side effect */
