Test `@mel.send` + `@mel.this`

  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > type 'a t = 'a array
  > external push : ?value:'a -> ('a t[@mel.this]) -> unit = "push" [@@mel.send]
  > external pushfirst : 'a t ->'a -> unit = "push" [@@mel.send]
  > let () =
  >   let arr = [| 0; 1; 2 |] in
  >   push arr ~value:3;
  >   pushfirst arr 3
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const arr = [
    0,
    1,
    2
  ];
  
  arr.push(3);
  
  arr.push(3);
  
  /*  Not a pure module */

Test: relax of `pushMany` to skip over [@mel.this]

  $ cat > x.ml <<EOF
  > type 'a t = 'a array
  > external pushMany : values:'a array -> ('a t[@mel.this]) -> unit = "push"
  > [@@mel.send] [@@mel.variadic]
  > let () =
  >   let arr = [| 0; 1; 2 |] in
  >   pushMany ~values:[|1;2|] arr
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const arr = [
    0,
    1,
    2
  ];
  
  arr.push(1, 2);
  
  /*  Not a pure module */
