A test that processes quoted strings in the same way that dune-merlin does

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let str foo = {j|Var is $foo|j};
  > EOF

  $ melc --as-pp x.ml > x.pp.ml
  $ melc --as-ppx x.pp.ml x.pp2.ml

  $ melc x.pp2.ml
  File "x.ml", line 1, characters 8-11:
  1 | let str foo = {j|Var is |j};
              ^^^
  Warning 27 [unused-var-strict]: unused variable foo.
  // Generated by Melange
  'use strict';
  
  
  function str(foo) {
    return "Var is ";
  }
  
  exports.str = str;
  /* No side effect */
