
  $ . ./setup.sh
  $ cat >x.ml <<EOF
  > let x = "hello"
  > EOF
  $ melc -nostdlib -nostdlib -nopervasives -nopervasives x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = "hello";
  
  module.exports = {
    x,
  }
  /* No side effect */
