Melange turns off warning 20 by default ([ignored-extra-argument])

  $ . ./setup.sh
  $ cat > dune-project <<EOF
  > (lang dune 3.8)
  > (using melange 0.1)
  > EOF
  $ cat > dune << EOF
  > (melange.emit
  >  (target out)
  >  (modules main)
  >  (libraries lib)
  >  (preprocess (pps melange.ppx)))
  > (library
  >  (name lib)
  >  (modules lib inner)
  >  (modes melange)
  >  (preprocess (pps melange.ppx)))
  > EOF

  $ cat > main.ml <<EOF
  > let foo = Lib.Inner.make()
  > EOF

  $ cat > lib.ml <<EOF
  > module Inner = Inner
  > EOF

  $ cat > lib.mli <<EOF
  > module Inner :
  > sig
  >   val make : unit -> unit
  > end

  $ cat > inner.ml <<EOF
  > [%%mel.raw {|
  >   var ErrorBoundary = function () {
  >     console.log("ErrorBoundary")
  >   };
  > |}]
  > 
  > external make: unit -> unit = "ErrorBoundary"
  > EOF

  $ dune build @melange

ErrorBoundary is referenced from Lib without being defined

  $ cat _build/default/out/lib.js
  // Generated by Melange
  'use strict';
  
  var Lib__Inner = require("./inner.js");
  
  var Inner = {
    make: (function (prim) {
        ErrorBoundary();
      })
  };
  
  exports.Inner = Inner;
  /* Lib__Inner Not a pure module */

  $ node _build/default/out/main.js
  $TESTCASE_ROOT/_build/default/out/lib.js:8
        ErrorBoundary();
        ^
  
  ReferenceError: ErrorBoundary is not defined
      at Object.make ($TESTCASE_ROOT/_build/default/out/lib.js:8:7)
      at Object.<anonymous> ($TESTCASE_ROOT/_build/default/out/main.js:6:21)
      at Module._compile (node:internal/modules/cjs/loader:1254:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:958:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
      at node:internal/main/run_main_module:23:47
  
  Node.js v18.16.0
  [1]

Adding `let make = make` fixes it

  $ cat > inner.ml <<EOF
  > [%%mel.raw {|
  >   var ErrorBoundary = function () {
  >     console.log("ErrorBoundary")
  >   };
  > |}]
  > 
  > external make: unit -> unit = "ErrorBoundary"
  > let make = make
  > EOF

  $ dune build @melange

  $ cat _build/default/out/lib.js
  // Generated by Melange
  'use strict';
  
  var Lib__Inner = require("./inner.js");
  
  var Inner = Lib__Inner;
  
  exports.Inner = Inner;
  /* Lib__Inner Not a pure module */

  $ node _build/default/out/main.js
  ErrorBoundary

