This tests checks that old `bs.*` attributes do not raise or warn, and also do nothing.

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type user = { this_will_remain : string [@bs.as "not_renamed"]; while_this_will_be_renamed : string [@mel.as "new_name"] }
  > let user = { this_will_remain = "Corentin"; while_this_will_be_renamed = "Belgium" }
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const user = {
    this_will_remain: "Corentin",
    new_name: "Belgium"
  };
  
  module.exports = {
    user,
  }
  /* No side effect */
