
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let pure x = x + 1
  > let x () =
  >   for _round = 1 to 10 do
  >     ignore (Sys.opaque_identity (pure 2))
  >   done
  > let () = x ()
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  function pure(x) {
    return x + 1 | 0;
  }
  
  function x(param) {
    for(let _round = 1; _round <= 10; ++_round){
      pure(2);
    }
  }
  
  x(undefined);
  
  exports.pure = pure;
  exports.x = x;
  /*  Not a pure module */
