Record payload options defined behind a module interface are unboxed before
field access.

  $ . ./setup.sh
  $ cat > dune-project <<'EOF'
  > (lang dune 3.21)
  > (using melange 1.0)
  > EOF
  $ cat > dune <<'EOF'
  > (melange.emit
  >  (target output)
  >  (emit_stdlib false)
  >  (modules tree x))
  > EOF
  $ cat > tree.mli <<'EOF'
  > type t = node option
  > and node = {
  >   value : int;
  >   height : int;
  >   left : t;
  >   right : t;
  > }
  > EOF
  $ cat > tree.ml <<'EOF'
  > type t = node option
  > and node = {
  >   value : int;
  >   height : int;
  >   left : t;
  >   right : t;
  > }
  > EOF
  $ cat > x.ml <<'EOF'
  > let fields (left : Tree.t) (right : Tree.t) =
  >   match left, right with
  >   | _, Some n -> Some (n.value, n.height, n.left, n.right)
  >   | _, None -> None
  > EOF

  $ dune build @melange

Melange generates `Caml_option.valFromOption` even if `right !== undefined`

  $ cat _build/default/output/x.js
  // Generated by Melange
  'use strict';
  
  const Caml_option = require("melange.js/caml_option.js");
  
  function fields(left, right) {
    if (right === undefined) {
      return;
    }
    const n = Caml_option.valFromOption(right);
    return [
      n.value,
      n.height,
      n.left,
      n.right
    ];
  }
  
  module.exports = {
    fields,
  }
  /* No side effect */
