Demonstrate usage of `--preamble`

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let x = 1
  > EOF

  $ melc x.ml --preamble '"use client";'
  "use client";
  // Generated by Melange
  'use strict';
  
  
  const x = 1;
  
  module.exports = {
    x,
  }
  /* No side effect */

  $ cat > x.ml <<EOF
  > [@@@mel.config { flags = [| "--preamble"; "\"use client\";" |] }]
  > let x = 1
  > EOF
  $ melc x.ml
  "use client";
  // Generated by Melange
  'use strict';
  
  
  const x = 1;
  
  module.exports = {
    x,
  }
  /* No side effect */


