Showcases how quoted strings work without melange.ppx

  $ . ./setup.sh

  $ cat > dune-project <<EOF
  > (lang dune 3.8)
  > (using melange 0.1)
  > EOF
  $ cat > dune <<EOF
  > (melange.emit
  >  (target out)
  >  (emit_stdlib false))
  > EOF

  $ cat > x.ml <<EOF
  > Js.log {js|🪄|js}
  > EOF

  $ dune build @melange

  $ cat _build/default/out/x.js
  // Generated by Melange
  'use strict';
  
  
  console.log("🪄");
  
  /*  Not a pure module */
