An external referring to a module-local raw JavaScript function must not be
relocated into another module, even when hidden behind an interface.

  $ . ./setup.sh

  $ cat > dune-project <<EOF
  > (lang dune 3.8)
  > (using melange 0.1)
  > EOF

  $ cat > dune <<EOF
  > (melange.emit
  >  (target dist)
  >  (emit_stdlib false)
  >  (preprocess (pps melange.ppx)))
  > EOF

  $ cat > bindings.ml <<EOF
  > [%%mel.raw {|function localHelper(value) { return value + 1; }|}]
  > external helper : int -> int = "localHelper"
  > let run x = helper x
  > EOF

  $ cat > bindings.mli <<EOF
  > val run : int -> int
  > EOF

  $ cat > main.ml <<EOF
  > let () = Js.log (Bindings.run 41)
  > EOF

  $ dune build @melange

The exported wrapper works when called from JavaScript.

  $ node -e 'console.log(require("./_build/default/dist/bindings.js").run(41))'
  42

The compiled OCaml caller should also print 42. Instead, the compiler relocates
the call to localHelper into main.js, where the helper is not defined.

  $ cat _build/default/dist/main.js
  // Generated by Melange
  'use strict';
  
  const Melange__Bindings = require("./bindings.js");
  
  console.log(localHelper(41));
  /*  Not a pure module */

  $ node <<'EOF'
  > try {
  >   require("./_build/default/dist/main.js");
  > } catch (error) {
  >   console.error(error.toString());
  >   process.exitCode = 1;
  > }
  > EOF
  ReferenceError: localHelper is not defined
  [1]
