
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let sum = function a -> function b -> a + b
  > let sum2 = fun a -> fun b -> a + b
  > let sum3 = fun (a, b) -> fun c -> a + b + c
  > let sum4 = fun a -> fun b -> fun c -> a + b + c
  > EOF

  $ melc -drawlambda x.ml
  (setglobal X!
    (let
      (sum/272 =
         (function a/274[int] (function b/275[int] : int (+ a/274 b/275)))
       sum2/276 =
         (function a/278[int] (function b/279[int] : int (+ a/278 b/279)))
       sum3/280 =
         (function param/285
           (let
             (b/283 =a (field_imm :[]/1 param/285)
              a/282 =a (field_imm :[]/0 param/285))
             (function c/284[int] : int (+ (+ a/282 b/283) c/284))))
       sum4/286 =
         (function a/288[int]
           (function b/289[int]
             (function c/290[int] : int (+ (+ a/288 b/289) c/290)))))
      (makeblock 0module/exports sum/272 sum2/276 sum3/280 sum4/286)))
  // Generated by Melange
  'use strict';
  
  
  function sum(a, b) {
    return a + b | 0;
  }
  
  function sum2(a, b) {
    return a + b | 0;
  }
  
  function sum3(param) {
    const b = param[1];
    const a = param[0];
    return function (c) {
      return (a + b | 0) + c | 0;
    };
  }
  
  function sum4(a, b, c) {
    return (a + b | 0) + c | 0;
  }
  
  module.exports = {
    sum,
    sum2,
    sum3,
    sum4,
  }
  /* No side effect */


  $ cat > x.ml <<EOF
  > let sum_optional = fun ?a -> fun b -> (Option.value ~default:0 a) + b
  > let sum_optional_default = fun ?(a=2) -> fun b -> a + b
  > EOF

  $ melc -drawlambda x.ml
  (setglobal X!
    (let
      (sum_optional/272 =
         (function a/274
           (function b/275[int] : int
             (+ (apply (field_mut :value/2 (global Stdlib__Option!)) a/274 0)
               b/275)))
       sum_optional_default/298 =
         (function *opt*/302
           (let
             (a/300 =[int]
                (if (#is_not_none *opt*/302)
                  (#val_from_unnest_option *opt*/302) 2))
             (function b/301[int] : int (+ a/300 b/301)))))
      (makeblock 0module/exports sum_optional/272 sum_optional_default/298)))
  // Generated by Melange
  'use strict';
  
  const Stdlib__Option = require("melange/option.js");
  
  function sum_optional(a, b) {
    return Stdlib__Option.value(a, 0) + b | 0;
  }
  
  function sum_optional_default(aOpt, b) {
    const a = aOpt !== undefined ? aOpt : 2;
    return a + b | 0;
  }
  
  module.exports = {
    sum_optional,
    sum_optional_default,
  }
  /* No side effect */
