
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let () = Format.printf {js|你 %s|js} "xx"
  > EOF
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  var Curry = require("melange.js/curry.js");
  var Stdlib__Format = require("melange/format.js");
  
  Curry._1(Stdlib__Format.printf(/* Format */{
            _0: {
              TAG: /* String_literal */11,
              _0: "\xe4\xbd\xa0 ",
              _1: {
                TAG: /* String */2,
                _0: /* No_padding */0,
                _1: /* End_of_format */0
              }
            },
            _1: "\xe4\xbd\xa0 %s"
          }), "xx");
  
  /*  Not a pure module */

