
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t
  > let x =
  >   let name = "tony" in
  >   {%j|\$name|}
  > 
  > let y = {%js|🐫|}
  > EOF

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  var x = "" + "tony";
  
  var y = "🐫";
  
  exports.x = x;
  exports.y = y;
  /* No side effect */
