
  $ . ./setup.sh

With PPX application

  $ cat > x.ml <<EOF
  > type saison = Hiver | Été | Printemps | Automne
  > let x = Été
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = /* Été */ 1;
  
  exports.x = x;
  /* No side effect */

With PPX application

  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = /* Été */ 1;
  
  exports.x = x;
  /* No side effect */

Add `@mel.as` string

  $ cat > x.ml <<EOF
  > type saison = Hiver | Été [@mel.as "Été"] | Printemps | Automne
  > let x = Été
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  
  const x = /* Été */ "Été";
  
  exports.x = x;
  /* No side effect */
