Showcase usage of escaped and literal unicode text in regular strings

  $ . ./setup.sh

  $ cat > dune-project <<EOF
  > (lang dune 3.15)
  > (using melange 0.1)
  > EOF
  $ cat > dune <<EOF
  > (melange.emit
  >  (target output)
  >  (alias mel)
  >  (emit_stdlib false)
  >  (preprocess (pps melange.ppx -alert -fragile)))
  > EOF

  $ cat > x.ml <<EOF
  > let s = "\u{1F42B}"
  > EOF

  $ dune build @mel
  $ cat _build/default/output/x.js
  // Generated by Melange
  'use strict';
  
  
  const s = "🐫";
  
  exports.s = s;
  /* No side effect */

  $ cat > x.ml <<EOF
  > let s = "🐫"
  > EOF

  $ dune build @mel
  $ cat _build/default/output/x.js
  // Generated by Melange
  'use strict';
  
  
  const s = "🐫";
  
  exports.s = s;
  /* No side effect */

Locations are broken

  $ cat > x.ml <<EOF
  > let q = "💩💩💩💩💩💩💩💩💩💩" ^ ("a" ^ 3 ^ "b")
  > EOF

  $ dune build @mel
  File "x.ml", line 1, characters 60-61:
  1 | let q = "💩💩💩💩💩💩💩💩💩💩" ^ ("a" ^ 3 ^ "b")
                                                                  ^
  Error: This expression has type int but an expression was expected of type
           string
  [1]
