Demonstrate the current prototype support for OCaml 5 effect primitives

  $ . ./setup.sh

%perform is an Effects primitive in OCaml 5

  $ cat > x.ml <<EOF
  > type 'a t
  > external perform : 'a t -> 'a = "%perform"
  > let () = perform (Obj.magic ())
  > EOF

  $ melc x.ml
  // Generated by Melange
  'use strict';
  
  const Caml_effect = require("melange.js/caml_effect.js");
  
  Caml_effect.caml_perform();
  /*  Not a pure module */
