
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  >   external mk : int ->
  > (
  >   [\`a|\`b]
  >    [@mel.string]
  > ) = "mk"
  > EOF
  $ melc -ppx melppx x.ml
  File "x.ml", line 4, characters 5-15:
  4 |    [@mel.string]
           ^^^^^^^^^^
  Alert unused: Unused attribute [@mel.string]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  // Generated by Melange
  /* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */


  $ cat > x.mli <<EOF
  >   [@@@mel.config { flags = [|"-unboxed-types"|] }]
  > EOF
  $ melc -ppx melppx x.mli
