
  $ . ./setup.sh
  $ cat > x.ml <<EOF
  >   external mk : int ->
  > (
  >   [\`a|\`b]
  >    [@bs.string]
  > ) = "mk" [@@bs.val]
  > EOF
  $ melc -ppx 'melppx -alert -deprecated' x.ml
  File "x.ml", line 4, characters 5-14:
  4 |    [@bs.string]
           ^^^^^^^^^
  Alert unused: Unused attribute [@bs.string]
  This means such annotation is not annotated properly.
  For example, some annotations are only meaningful in externals
  
  // Generated by Melange
  /* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */


  $ cat > x.mli <<EOF
  >   [@@@mel.config { flags = [|"-unboxed-types"|] }]
  > EOF
  $ melc -ppx melppx x.mli
