Show PPX warnings don't respect `-warn-error`

Regular warnings can be fatal

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > let x =
  >   let y = 3 in
  >   4
  > EOF
  $ melc -warn-error +26 x.ml
  File "x.ml", line 2, characters 6-7:
  2 |   let y = 3 in
            ^
  Error (warning 26 [unused-var]): unused variable y.
  [2]

Warnings originating from `melange.ppx` don't respect `-warn-error`

  $ cat > x.ml <<EOF
  > let x = [%raw {| ( |}]
  > EOF
  $ melc -ppx melppx -warn-error +103 x.ml
  File "x.ml", line 1, characters 19-19:
  Warning 103 [melange-ffi-warning]: FFI warning: Unexpected end of input
  // Generated by Melange
  'use strict';
  
  
  const x = (;
  
  module.exports = {
    x,
  }
  /* No side effect */
