
  $ . ./setup.sh

  $ cat > x.ml <<EOF
  > let foo a =
  >   let a = Some a in
  >   match a with
  >   | Some true -> "it's true"
  >   | _ -> "it's false"
  > let _ = Js.log (foo false)
  > EOF

  $ melc x.ml | tee x.js
  // Generated by Melange
  'use strict';
  
  
  function foo(a) {
    const a$1 = a;
    if (a$1) {
      return "it's true";
    } else {
      return "it's false";
    }
  }
  
  console.log("it's false");
  
  module.exports = {
    foo,
  }
  /*  Not a pure module */

  $ node x.js
  it's false

$ cat > x.ml <<EOF
> let foo a =
>   let a = Some a in
>   match a with
>   | Some true -> "it's true"
>   | _ -> "it's false"
> EOF

$ melc x.ml | tee x.js
$ node x.js
