name: Build using esy (arm64)

on:
  pull_request:
  push:
    branches:
      - fork

jobs:
  build:
    name: Build

    strategy:
      matrix:
        system: [macos-arm64]

    runs-on: ${{ matrix.system }}-latest

    steps:
      - uses: actions/checkout@v3
      - uses: esy/github-action@master
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

      - name: Run tests.
        if: ${{ matrix.system != 'windows' }}
        run: esy test
